kind = "api"
previewPath = "/api"
title = "REST Server"
version = "1.0.0"
id = "3B4_FFSkEVBkAeYMFRJ2e"

[[services]]
localPort = 8080
name = "REST Server"
paths = ["/"]

[services.development]
run = "pnpm --filter @workspace/rest-server run dev"

[services.production]

[services.production.build]
args = ["pnpm", "--filter", "@workspace/rest-server", "run", "build"]

[services.production.build.env]
NODE_ENV = "production"

[services.production.run]
# we don't run through pnpm to make startup faster in production
args = ["node", "--enable-source-maps", "artifacts/rest-server/dist/index.mjs"]

[services.production.run.env]
PORT = "8080"
NODE_ENV = "production"

[services.production.health.startup]
path = "/api/healthz"
