import React, { useMemo } from "react";
import {
  useGetSourcesIndex,
  getGetSourcesIndexQueryKey,
  type SourceSummary,
} from "@workspace/api-client-react";
import { Layout } from "@/components/Layout";
import { SourceCard } from "@/components/SourceCard";
import { ServerCrash, Loader2, DatabaseZap } from "lucide-react";
import { motion } from "framer-motion";

const GROUP_ORDER = [
  "source_wrapper",
  "derived_synthesis",
  "aggregation",
  "system",
] as const;

const GROUP_LABELS: Record<string, string> = {
  source_wrapper: "Source Wrappers",
  derived_synthesis: "Derived Synthesis",
  aggregation: "Aggregations",
  system: "System Components",
};

const GROUP_DESCRIPTIONS: Record<string, string> = {
  source_wrapper:
    "Direct adapters wrapping external authoritative datasets with FERNS standard interfaces.",
  derived_synthesis:
    "Higher-order insights generated by combining and analyzing multiple data sources.",
  aggregation:
    "Combined datasets merging multiple sources into a single unified endpoint.",
  system: "Internal registry and routing services powering FERNS.",
};

export default function Home() {
  const { data, isLoading, isError, error } = useGetSourcesIndex({
    query: { queryKey: getGetSourcesIndexQueryKey() },
  });

  const groupedSources = useMemo(() => {
    if (!data?.data?.sources) return null;

    const groups = data.data.sources.reduce(
      (acc, source) => {
        const type = source.knowledge_type;
        if (!acc[type]) acc[type] = [];
        acc[type].push(source);
        return acc;
      },
      {} as Record<string, SourceSummary[]>,
    );

    return groups;
  }, [data]);

  return (
    <Layout>
      <div className="mb-12 md:mb-16 max-w-3xl">
        <motion.h2
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          className="text-4xl md:text-5xl font-bold text-foreground mb-4 tracking-tight"
        >
          Explore FERNS Sources
        </motion.h2>
        <motion.p
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.1 }}
          className="text-lg text-muted-foreground leading-relaxed"
        >
          Discover registered knowledge services, datasets, and synthesis
          endpoints described by FERNS.
        </motion.p>
      </div>
      {isLoading && (
        <div className="flex flex-col items-center justify-center py-24 text-primary">
          <Loader2 className="w-12 h-12 animate-spin mb-4" />
          <p className="text-muted-foreground font-medium animate-pulse">
            Scanning registry...
          </p>
        </div>
      )}
      {isError && (
        <div className="bg-destructive/5 border border-destructive/20 rounded-2xl p-8 flex flex-col items-center justify-center text-center max-w-2xl mx-auto">
          <div className="bg-destructive/10 p-4 rounded-full mb-4">
            <ServerCrash className="w-10 h-10 text-destructive" />
          </div>
          <h3 className="text-xl font-bold text-destructive mb-2">
            Failed to load registry
          </h3>
          <p className="text-muted-foreground mb-4">
            {error instanceof Error
              ? error.message
              : "The FERNS registry service is currently unreachable."}
          </p>
          <button
            onClick={() => window.location.reload()}
            className="px-6 py-2.5 bg-background border border-border rounded-xl text-sm font-semibold hover:bg-muted transition-colors"
          >
            Try Again
          </button>
        </div>
      )}
      {!isLoading &&
        !isError &&
        groupedSources &&
        Object.keys(groupedSources).length === 0 && (
          <div className="bg-card border border-border rounded-3xl p-12 flex flex-col items-center justify-center text-center shadow-sm">
            <div className="bg-muted p-5 rounded-2xl mb-6">
              <DatabaseZap className="w-12 h-12 text-muted-foreground" />
            </div>
            <h3 className="text-2xl font-bold text-foreground mb-3">
              Registry is Empty
            </h3>
            <p className="text-muted-foreground max-w-md">
              No sources are currently registered in the system. Check the
              database configuration or run the seeding scripts.
            </p>
          </div>
        )}
      {!isLoading && !isError && groupedSources && (
        <div className="space-y-16">
          {GROUP_ORDER.map((groupType) => {
            const sources = groupedSources[groupType];
            if (!sources || sources.length === 0) return null;

            return (
              <section key={groupType} className="scroll-mt-24">
                <div className="mb-8 pb-4 border-b border-border/60">
                  <h3 className="text-2xl font-bold text-foreground flex items-center gap-3">
                    {GROUP_LABELS[groupType] || groupType}
                    <span className="text-sm font-mono font-medium bg-primary/10 text-primary px-3 py-1 rounded-full">
                      {sources.length}
                    </span>
                  </h3>
                  <p className="text-muted-foreground mt-2 font-medium">
                    {GROUP_DESCRIPTIONS[groupType]}
                  </p>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-6 lg:gap-8">
                  {sources.map((source, idx) => (
                    <SourceCard
                      key={source.source_id}
                      source={source}
                      index={idx}
                    />
                  ))}
                </div>
              </section>
            );
          })}

          {/* Render any unknown types that aren't in GROUP_ORDER */}
          {Object.keys(groupedSources)
            .filter((key) => !(GROUP_ORDER as readonly string[]).includes(key))
            .map((groupType) => {
              const sources = groupedSources[groupType];
              return (
                <section key={groupType} className="scroll-mt-24">
                  <div className="mb-8 pb-4 border-b border-border/60">
                    <h3 className="text-2xl font-bold text-foreground capitalize">
                      {groupType.replace(/_/g, " ")}
                    </h3>
                  </div>
                  <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-6 lg:gap-8">
                    {sources.map((source, idx) => (
                      <SourceCard
                        key={source.source_id}
                        source={source}
                        index={idx}
                      />
                    ))}
                  </div>
                </section>
              );
            })}
        </div>
      )}
    </Layout>
  );
}
