import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import bonapRouter from "./bonap.js";
import gbifRouter from "./gbif.js";
import inatRouter from "./inat.js";
import mifloraRouter from "./miflora.js";
import coefficientRouter from "./coefficient.js";
import wetlandIndicatorRouter from "./wetland-indicator.js";
import wucolsRouter from "./wucols.js";
import s2cRouter from "./s2c.js";
import universalFqaRouter from "./universal-fqa.js";
import lcscgRouter from "./lcscg.js";
import mnfiRouter from "./mnfi.js";
import natureserveRouter from "./natureserve.js";
import registryRouter from "./registry.js";
import specRouter from "./spec.js";
import gobotanyRouter from "./gobotany.js";
import googleImagesRouter from "./google-images.js";
import missouriPlantsRouter from "./missouri-plants.js";
import minnesotaWildflowersRouter from "./minnesota-wildflowers.js";
import illinoisWildflowersRouter from "./illinois-wildflowers.js";
import prairieMoonRouter from "./prairie-moon.js";
import usdaPlantsRouter from "./usda-plants.js";
import ladyBirdJohnsonRouter from "./lady-bird-johnson.js";
import botanicalRefsRouter from "./botanical-refs.js";
import sourceRelationshipsRouter from "./source-relationships.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use(bonapRouter);
router.use(gbifRouter);
router.use(inatRouter);
router.use(mifloraRouter);
router.use(coefficientRouter);
router.use(wetlandIndicatorRouter);
router.use(wucolsRouter);
router.use(s2cRouter);
router.use(universalFqaRouter);
router.use(lcscgRouter);
router.use(mnfiRouter);
router.use(natureserveRouter);
router.use(gobotanyRouter);
router.use(googleImagesRouter);
router.use(missouriPlantsRouter);
router.use(minnesotaWildflowersRouter);
router.use(illinoisWildflowersRouter);
router.use(prairieMoonRouter);
router.use(usdaPlantsRouter);
router.use(ladyBirdJohnsonRouter);
router.use(botanicalRefsRouter);
router.use(sourceRelationshipsRouter);
router.use(registryRouter);
router.use(specRouter);

export default router;
