// AUTO-GENERATED by lib/internal-data-providers/src/mnfi/scraper — do not edit manually.
// Scraped from https://mnfi.anr.msu.edu on 2026-06-29.

export interface AbstractRecord {
  subjectType: "community" | "animal" | "plant" | "other";
  subjectKey: number | null;
  name: string;
  pdfUrl: string;
}

export const MNFI_ABSTRACTS: AbstractRecord[] = [
  {
    subjectType: "animal",
    subjectKey: 11270,
    name: "Acipenser fulvescens",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Acipenser_fulvescens.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 10848,
    name: "Acris blanchardi",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Acris_crepitans_blanchardi.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 12351,
    name: "Alasmidonta marginata",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Alasmidonta_marginata.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 10833,
    name: "Ambystoma opacum",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Ambystoma_opacum.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 10835,
    name: "Ambystoma texanum",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Ambystoma_texanum.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 11397,
    name: "Ammocrypta pellucida",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Ammocrypta_pellucida.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 11220,
    name: "Ammodramus savannarum",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Ammodramus_savannarum.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 12247,
    name: "Appalachia arcana",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Appalachia_arcana.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 12506,
    name: "Appalachina sayanus",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Appalachina_sayanus.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 11066,
    name: "Asio flammeus",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Asio_flammeus.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 11065,
    name: "Asio otus",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Asio_otus.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 10941,
    name: "Astur atricapillus",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Accipiter_gentilis.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 11622,
    name: "Atrytonopsis hianna",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Atrytonopsis_hianna.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 10988,
    name: "Bartramia longicauda",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Bartramia_longicauda.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 11706,
    name: "Boloria freija",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Boloria_freija.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 365143,
    name: "Bombus pensylvanicus",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Bombus_pensylvanicus.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 10877,
    name: "Botaurus exilis",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Ixobrychus_exilis.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 10876,
    name: "Botaurus lentiginosus",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Botaurus_lentiginosus.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 11555,
    name: "Brychius hungerfordi",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Brychius_hungerfordi.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 10942,
    name: "Buteo lineatus",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Buteo_lineatus.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 11693,
    name: "Calephelis muticum",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Calephelis_mutica.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 11672,
    name: "Callophrys irus",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Incisalia_irus.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 420819,
    name: "Cambarunio iris",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Villosa_iris.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 10957,
    name: "Canachites canadensis",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Falcipennis_canadensis.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 11221,
    name: "Centronyx henslowii",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Ammodramus_henslowii.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 10978,
    name: "Charadrius melodus",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Charadrius_melodus.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 11043,
    name: "Chlidonias niger",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Chlidonias_niger.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 11330,
    name: "Chrosomus erythrogaster",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Phoxinus_erythrogaster.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 10938,
    name: "Circus hudsonius",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Circus_cyaneus.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 11126,
    name: "Cistothorus palustris",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Cistothorus_palustris.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 11125,
    name: "Cistothorus platensis",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Cistothorus_platensis.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 11488,
    name: "Clemmys guttata",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Clemmys_guttata.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 11307,
    name: "Clinostomus elongatus",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Clinostomus_elongatus.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 11499,
    name: "Clonophis kirtlandii",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Clonophis_kirtlandii.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 11259,
    name: "Coccothraustes vespertinus",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Coccothraustes_vespertinus.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 11279,
    name: "Coregonus artedi",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Coregonus_artedi.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 10965,
    name: "Coturnicops noveboracensis",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Coturnicops_noveboracensis.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 12356,
    name: "Cyclonaias tuberculata",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Cyclonaias_tuberculata.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 11490,
    name: "Emydoidea blandingii",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Emydoidea_blandingii.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 12362,
    name: "Epioblasma perobliqua",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Epioblasma_obliquata_perobliqua.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 12364,
    name: "Epioblasma rangiana",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Epioblasma_torulosa_rangiana.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 12365,
    name: "Epioblasma triquetra",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Epioblasma_triquetra.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 11748,
    name: "Erebia discoidalis",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Erebia_discoidalis.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 11319,
    name: "Ericymba dorsalis",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Notropis_dorsalis.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 11586,
    name: "Erynnis persius persius",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Erynnis_persius_persius.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 11404,
    name: "Etheostoma spectabile",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Etheostoma_spectabile.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 12482,
    name: "Euconulus alderi",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Euconulus_alderi.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 11616,
    name: "Euphyes dukesi",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Euphyes_dukesi.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 12038,
    name: "Euxoa aurulenta",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Euxoa_aurulenta.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 10951,
    name: "Falco columbarius",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Falco_columbarius.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 10952,
    name: "Falco peregrinus",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Falco_peregrinus.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 11530,
    name: "Faxonius immunis",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Faxonius_immunis.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 11563,
    name: "Flexamia reflexa",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Flexamia_reflexa.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 12529,
    name: "Fontigens nickliniana",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Fontigens_nickliniana.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 10971,
    name: "Gallinula galeata",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Gallinula_galeata.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 10862,
    name: "Gavia immer",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Gavia_immer.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 11489,
    name: "Glyptemys insculpta",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Glyptemys_insculpta.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 10937,
    name: "Haliaeetus leucocephalus",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Haliaeetus_leucocephalus.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 12426,
    name: "Hendersonia occulta",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Hendersonia_occulta.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 11599,
    name: "Hesperia ottoe",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Hesperia_ottoe.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 11278,
    name: "Hiodon tergisus",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Hiodon_tergisus.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 11038,
    name: "Hydroprogne caspia",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Sterna_caspia.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 11138,
    name: "Hylocichla mustelina",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Hylocichla_mustelina.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 12367,
    name: "Lampsilis fasciola",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Lampsilis_fasciola.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 11150,
    name: "Lanius ludovicianus migrans",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Lanius_ludovicianus_migrans.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 12371,
    name: "Lasmigona compressa",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Lasmigona_compressa.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 12372,
    name: "Lasmigona costata",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Lasmigona_costata.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 11272,
    name: "Lepisosteus oculatus",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Lepisosteus_oculatus.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 12376,
    name: "Ligumia recta",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Ligumia_recta.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 10857,
    name: "Lithobates palustris",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Lithobates_palustris.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 11341,
    name: "Macrhybopsis storeriana",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Macrhybopsis_storeriana.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 12478,
    name: "Mediappendix exilis",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Catinella_exile.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 18916,
    name: "Mediappendix protracta",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Mediappendix_protracta.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 12502,
    name: "Mesodon elevatus",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Mesodon_elevatus.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 11451,
    name: "Microtus ochrogaster",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Microtus_ochrogaster.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 11452,
    name: "Microtus pinetorum",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Microtus_pinetorum.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 11316,
    name: "Miniellus anogenus",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Notropis_anogenus.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 11356,
    name: "Moxostoma carinatum",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Moxostoma_carinatum.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 11425,
    name: "Myotis lucifugus",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Myotis_lucifugus.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 11427,
    name: "Myotis septentrionalis",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Myotis_septentrionalis.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 10841,
    name: "Necturus maculosus",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Necturus_maculosus.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 11743,
    name: "Neonympha mitchellii mitchellii",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Neonympha_mitchellii_mitchellii.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 11509,
    name: "Nerodia erythrogaster neglecta",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Nerodia_erythrogaster_neglecta.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 11323,
    name: "Notropis photogenis",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Notropis_photogenis.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 11366,
    name: "Noturus miurus",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Noturus_miurus.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 11367,
    name: "Noturus stigmosus",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Noturus_stigmosus.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 10885,
    name: "Nycticorax nycticorax",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Nycticorax_nycticorax.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 11594,
    name: "Oarisma poweshiek",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Oarisma_poweshiek.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 12377,
    name: "Obliquaria reflexa",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Obliquaria_reflexa.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 12378,
    name: "Obovaria olivaria",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Obovaria_olivaria.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 12379,
    name: "Obovaria subrotunda",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Obovaria_subrotunda.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 11517,
    name: "Opheodrys vernalis",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Opheodrys_vernalis.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 12083,
    name: "Ophiogomphus anomalus",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Ophiogomphus_anomalus.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 12087,
    name: "Ophiogomphus howei",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Ophiogomphus_howei.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 11192,
    name: "Oporornis agilis",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Oporornis_agilis.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 11343,
    name: "Opsopoeodus emiliae",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Opsopoeodus_emiliae.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 12394,
    name: "Paetulunio fabalis",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Paetulunio_fabalis.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 10934,
    name: "Pandion haliaetus",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Pandion_haliaetus.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 11505,
    name: "Pantherophis gloydi",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Pantherophis_gloydi.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 11503,
    name: "Pantherophis spiloides",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Pantherophis_spiloides.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 11991,
    name: "Papaipema beeriana",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Papaipema_beeriana.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 11989,
    name: "Papaipema sciata",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Papaipema_sciata.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 11982,
    name: "Papaipema silphii",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Papaipema_silphii.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 11971,
    name: "Papaipema speciosissima",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Papaipema_speciosissima.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 11190,
    name: "Parkesia motacilla",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Seiurus_motacilla.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 11408,
    name: "Percina copelandi",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Percina_copelandi.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 11410,
    name: "Percina shumardi",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Percina_shumardi.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 11083,
    name: "Picoides arcticus",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Picoides_arcticus.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 12451,
    name: "Planogyra asteriscus",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Planogyra_asteriscus.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 11689,
    name: "Plebejus idas nabokovi",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Lycaeides_idas_nabokovi.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 11691,
    name: "Plebejus samuelis",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Lycaeides_melissa_samuelis.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 12380,
    name: "Pleurobema clava",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Pleurobema_clava.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 12381,
    name: "Pleurobema sintoxia",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Pleurobema_sintoxia.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 11115,
    name: "Poecile hudsonicus",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Poecile_hudsonicus.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 12352,
    name: "Pressodonta viridis",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Alasmidonta_viridis.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 11185,
    name: "Protonotaria citrea",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Protonotaria_citrea.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 365147,
    name: "Pyrgus centaureae wyandot",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Pyrgus_wyandot.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 10967,
    name: "Rallus elegans",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Rallus_elegans.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 11511,
    name: "Regina septemvittata",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Regina_septemvittata.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 12375,
    name: "Sagittunio nasutus",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Sagittunio_nasutus.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 11411,
    name: "Sander canadensis",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Sander_canadensis.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 12056,
    name: "Schinia indiana",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Schinia_indiana.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 12057,
    name: "Schinia lucens",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Schinia_lucens.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 11182,
    name: "Setophaga cerulea",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Dendroica_cerulea.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 11178,
    name: "Setophaga discolor",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Dendroica_discolor.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 11177,
    name: "Setophaga kirtlandii",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Dendroica_kirtlandii.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 12388,
    name: "Simpsonaias ambigua",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Simpsonaias_ambigua.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 11519,
    name: "Sistrurus catenatus",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Sistrurus_catenatus.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 12124,
    name: "Somatochlora hineana",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Somatochlora_hineana.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 12125,
    name: "Somatochlora incurvata",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Somatochlora_incurvata.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 11208,
    name: "Spiza americana",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Spiza_americana.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 11041,
    name: "Sterna forsteri",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Sterna_forsteri.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 11039,
    name: "Sterna hirundo",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Sterna_hirundo.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 12215,
    name: "Stylurus amnicola",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Stylurus_amnicola.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 12217,
    name: "Stylurus notatus",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Stylurus_notatus.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 12218,
    name: "Stylurus plagiatus",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Stylurus_plagiatus.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 11493,
    name: "Terrapene carolina carolina",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Terrapene_carolina.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 11514,
    name: "Thamnophis butleri",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Thamnophis_butleri.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 12390,
    name: "Toxolasma lividus",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Toxolasma_lividus.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 12391,
    name: "Toxolasma parvum",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Toxolasma_parvum.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 12268,
    name: "Trimerotropis huroniana",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Trimerotropis_huroniana.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 12392,
    name: "Truncilla donaciformis",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Truncilla_donaciformis.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 10962,
    name: "Tympanuchus phasianellus",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Tympanuchus_phasianellus.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 12425,
    name: "Venustaconcha ellipsiformis",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Venustaconcha_ellipsiformis.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 12437,
    name: "Vertigo bollesiana",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Vertigo_bollesiana.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 12450,
    name: "Vertigo cristata",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Vertigo_cristata.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 12438,
    name: "Vertigo elatior",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Vertigo_elatior.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 12441,
    name: "Vertigo modesta parietalis",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Vertigo_modesta_parietalis.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 12442,
    name: "Vertigo morsei",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Vertigo_morsei.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 12443,
    name: "Vertigo nylanderi",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Vertigo_nylanderi.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 12449,
    name: "Vertigo paradoxa",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Vertigo_paradoxa.pdf"
  },
  {
    subjectType: "animal",
    subjectKey: 11242,
    name: "Xanthocephalus xanthocephalus",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Xanthocephalus_xanthocephalus.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 14230,
    name: "Adlumia fungosa",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Adlumia_fungosa.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 14903,
    name: "Agalinis gattingeri",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Agalinis_gattingeri.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 14905,
    name: "Agalinis skinneriana",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Agalinis_skinneriana.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 13396,
    name: "Agoseris glauca",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Agoseris_glauca.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 14108,
    name: "Amorpha canescens",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Amorpha_canescens.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 15569,
    name: "Aristida longespica",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Aristida_longespica.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 13411,
    name: "Arnica cordifolia",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Arnica_cordifolia.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 13675,
    name: "Arnoglossum plantagineum",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Cacalia_plantaginea.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 417357,
    name: "Artemisia serrata",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Artemisia_serrata.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 13381,
    name: "Asclepias hirtella",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Asclepias_hirtella.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 13384,
    name: "Asclepias purpurascens",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Asclepias_purpurascens.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 13386,
    name: "Asclepias sullivantii",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Asclepias_sullivantii.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 15870,
    name: "Asplenium rhizophyllum",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Asplenium_rhizophyllum.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 15873,
    name: "Asplenium scolopendrium var. americanum",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Asplenium_scolopendrium.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 14118,
    name: "Baptisia lactea",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Baptisia_lactea.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 14237,
    name: "Bartonia paniculata",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Bartonia_paniculata.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 15577,
    name: "Beckmannia syzigachne",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Beckmannia_syzigachne.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 14537,
    name: "Bistorta vivipara",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Polygonum_viviparum.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 364991,
    name: "Boechera dentata",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Boechera_dentata.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 13752,
    name: "Boechera missouriensis",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Boechera_missouriensis.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 15957,
    name: "Botrychium campestre",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Botrychium_campestre.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 15955,
    name: "Botrychium michiganense",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Botrychium_hesperium.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 15953,
    name: "Botrychium mormo",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Botrychium_mormo.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 15578,
    name: "Bouteloua curtipendula",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Bouteloua_curtipendula.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 15587,
    name: "Bromus pumpellianus",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Bromus_pumpellianus.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 15499,
    name: "Calypso bulbosa",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Calypso_bulbosa.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 13433,
    name: "Canadanthus modestus",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Aster_modestus.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 13782,
    name: "Cardamine maxima",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Dentaria_maxima.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 15122,
    name: "Carex assiniboinensis",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Carex_assiniboinensis.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 15126,
    name: "Carex atratiformis",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Carex_atratiformis.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 15210,
    name: "Carex lupuliformis",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Carex_lupuliformis.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 15234,
    name: "Carex platyphylla",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Carex_platyphylla.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 15243,
    name: "Carex richardsonii",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Carex_richardsonii.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 14914,
    name: "Castilleja septentrionalis",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Castilleja_septentrionalis.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 14656,
    name: "Ceanothus sanguineus",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Ceanothus_sanguineus.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 14917,
    name: "Chelone obliqua",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Chelone_obliqua.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 13482,
    name: "Cirsium hillii",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Cirsium_hillii.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 13485,
    name: "Cirsium pitcheri",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Cirsium_pitcheri.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 14920,
    name: "Collinsia verna",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Collinsia_verna.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 14638,
    name: "Coptidium lapponicum",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Ranunculus_lapponicus.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 13491,
    name: "Coreopsis palmata",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Coreopsis_palmata.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 14232,
    name: "Corydalis flavula",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Corydalis_flavula.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 15506,
    name: "Cypripedium arietinum",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Cypripedium_arietinum.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 15507,
    name: "Cypripedium candidum",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Cypripedium_candidum.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 14722,
    name: "Dalibarda repens",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Dalibarda_repens.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 15633,
    name: "Dichanthelium leibergii",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Dichanthelium_leibergii.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 15639,
    name: "Dichanthelium polyanthes",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Dichanthelium_polyanthes.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 13792,
    name: "Draba arabisans",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Draba_arabisans.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 14052,
    name: "Drosera anglica",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Drosera_anglica.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 15894,
    name: "Dryopteris fragrans",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Dryopteris_fragrans.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 14061,
    name: "Empetrum nigrum",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Empetrum_nigrum.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 13377,
    name: "Endodeca serpentaria",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Aristolochia_serpentaria.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 417360,
    name: "Eriophorum russeolum",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Eriophorum_russeolum.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 13332,
    name: "Eryngium yuccifolium",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Eryngium_yuccifolium.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 13917,
    name: "Euonymus atropurpureus",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Euonymus_atropurpurea.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 13517,
    name: "Eupatorium sessilifolium",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Eupatorium_sessilifolium.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 14097,
    name: "Euphorbia commutata",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Euphorbia_commutata.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 13512,
    name: "Eutrochium fistulosum",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Eupatorium_fistulosum.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 14724,
    name: "Filipendula rubra",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Filipendula_rubra.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 15336,
    name: "Fimbristylis puberula",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Fimbristylis_puberula.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 14447,
    name: "Fraxinus profunda",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Fraxinus_profunda.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 19819,
    name: "Fuirena pumila",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Fuirena_pumila.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 15495,
    name: "Galearis rotundifolia",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Amerorchis_rotundifolia.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 15511,
    name: "Galearis spectabilis",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Galearis_spectabilis.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 14242,
    name: "Gentiana flavida",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Gentiana_flavida.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 14248,
    name: "Gentianella quinquefolia",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Gentianella_quinquefolia.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 14732,
    name: "Geum triflorum",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Geum_triflorum.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 14930,
    name: "Gratiola virginiana",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Gratiola_virginiana.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 15901,
    name: "Gymnocarpium robertianum",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Gymnocarpium_robertianum.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 13537,
    name: "Helianthus hirsutus",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Helianthus_hirsutus.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 13556,
    name: "Hieracium paniculatum",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Hieracium_paniculatum.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 14625,
    name: "Hydrastis canadensis",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Hydrastis_canadensis.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 13963,
    name: "Hypericum gentianoides",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Hypericum_gentianoides.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 15374,
    name: "Iris lacustris",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Iris_lacustris.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 15517,
    name: "Isotria verticillata",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Isotria_verticillata.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 15395,
    name: "Juncus brachycarpus",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Juncus_brachycarpus.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 15410,
    name: "Juncus scirpoides",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Juncus_scirpoides.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 15415,
    name: "Juncus vaseyi",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Juncus_vaseyi.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 13277,
    name: "Justicia americana",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Justicia_americana.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 15801,
    name: "Leymus mollis",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Leymus_mollis.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 14382,
    name: "Linum virginianum",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Linum_virginianum.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 15420,
    name: "Luzula parviflora",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Luzula_parviflora.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 15942,
    name: "Lycopodiella subappressa",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Lycopodiella_subappressa.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 14330,
    name: "Lycopus virginicus",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Lycopus_virginicus.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 13726,
    name: "Mertensia virginica",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Mertensia_virginica.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 14940,
    name: "Mimulus alatus",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Mimulus_alatus.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 14943,
    name: "Mimulus michiganensis",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Mimulus_michiganensis.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 417362,
    name: "Monarda clinopodia",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Mondarda_clinopodia.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 14431,
    name: "Morus rubra",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Morus_rubra.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 15713,
    name: "Muhlenbergia richardsonis",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Muhlenbergia_richardsonis.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 14485,
    name: "Orobanche fasciculata",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Orobanche_fasciculata.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 13616,
    name: "Packera indecora",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Senecio_indecorus.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 13373,
    name: "Panax quinquefolius",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Panax_quinquefolius.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 14896,
    name: "Parnassia palustris",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Parnassia_palustris.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 15866,
    name: "Pellaea atropurpurea",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Pellaea_atropurpurea.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 14951,
    name: "Penstemon calycosus",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Penstemon_calycosus.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 417363,
    name: "Persicaria robustior",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Persicaria_robustior.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 13599,
    name: "Petasites frigidus var. sagittatus",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Petasites_sagittatus.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 14292,
    name: "Phacelia franklinii",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Phacelia_franklinii.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 14383,
    name: "Pinguicula vulgaris",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Pinguicula_vulgaris.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 15720,
    name: "Piptatherum canadense",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Oryzopsis_canadensis.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 14565,
    name: "Plantago cordata",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Plantago_cordata.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 15527,
    name: "Platanthera ciliaris",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Platanthera_ciliaris.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 15534,
    name: "Platanthera leucophaea",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Platanthera_leucophaea.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 15742,
    name: "Poa alpina",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Poa_alpina.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 14562,
    name: "Polemonium reptans",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Polemonium_reptans.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 14504,
    name: "Polygala incarnata",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Polygala_incarnata.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 14857,
    name: "Populus heterophylla",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Populus_heterophylla.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 15812,
    name: "Potamogeton confervoides",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Potamogeton_confervoides.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 15819,
    name: "Potamogeton hillii",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Potamogeton_hillii.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 14580,
    name: "Primula meadia",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Dodecatheon_meadia.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 15447,
    name: "Prosartes hookeri",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Prosartes_hookeri.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 14283,
    name: "Proserpinaca pectinata",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Proserpinaca_pectinata.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 14754,
    name: "Prunus umbellata",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Prunus_alleghaniensis.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 14428,
    name: "Pterospora andromedea",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Pterospora_andromedea.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 14348,
    name: "Pycnanthemum verticillatum",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Pycnanthemum_verticillatum.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 14630,
    name: "Ranunculus ambigens",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Ranunculus_ambigens.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 14645,
    name: "Ranunculus rhomboideus",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Ranunculus_rhomboideus.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 14422,
    name: "Rhexia virginica",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Rhexia_virginica.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 13756,
    name: "Rorippa aquatica",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Armoracia_lacustris.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 14252,
    name: "Sabatia angularis",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Sabatia_angularis.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 13883,
    name: "Sagina nodosa",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Sagina_nodosa.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 14898,
    name: "Saxifraga paniculata",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Saxifraga_paniculata.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 14900,
    name: "Saxifraga tricuspidata",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Saxifraga_tricuspidata.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 15354,
    name: "Schoenoplectiella hallii",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Schoenoplectus_hallii.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 15364,
    name: "Scleria pauciflora",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Scleria_pauciflora.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 13896,
    name: "Silene stellata",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Silene_stellata.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 13622,
    name: "Silphium integrifolium",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Silphium_integrifolium.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 13623,
    name: "Silphium laciniatum",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Silphium_laciniatum.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 13624,
    name: "Silphium perfoliatum",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Silphium_perfoliatum.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 15388,
    name: "Sisyrinchium strictum",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Sisyrinchium_strictum.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 13671,
    name: "Smallanthus uvedalia",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Polymnia_uvedalia.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 13632,
    name: "Solidago houghtonii",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Solidago_houghtonii.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 15778,
    name: "Sporobolus clandestinus",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Sporobolus_clandestinus.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 15780,
    name: "Sporobolus heterolepis",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Sporobolus_heterolepis.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 13908,
    name: "Stellaria longipes",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Stellaria_longipes.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 14911,
    name: "Synthyris bullii",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Synthyris_bullii.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 13654,
    name: "Tanacetum bipinnatum ssp. huronense",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Tanacetum_huronense.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 13678,
    name: "Tetraneuris herbacea",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Hymenoxys_herbacea.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 14371,
    name: "Trichostema dichotomum",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Trichostema_dichotomum.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 15482,
    name: "Trillium recurvatum",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Trillium_recurvatum.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 15483,
    name: "Trillium sessile",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Trillium_sessile.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 15484,
    name: "Trillium undulatum",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Trillium_undulatum.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 15792,
    name: "Trisetum spicatum",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Trisetum_spicatum.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 417365,
    name: "Utricularia ochroleuca",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Utricularia_ochroleuca.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 14392,
    name: "Utricularia subulata",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Utricularia_subulata.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 14075,
    name: "Vaccinium cespitosum",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Vaccinium_cespitosum.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 15022,
    name: "Valeriana edulis var. ciliata",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Valeriana_edulis_var_ciliata.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 14019,
    name: "Viburnum edule",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Viburnum_edule.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 15050,
    name: "Viola pedatifida",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Viola_pedatifida.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 417367,
    name: "Wolffiella gladiata",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Wolffiella_gladiata.pdf"
  },
  {
    subjectType: "plant",
    subjectKey: 15796,
    name: "Zizania aquatica",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/botany/Zizania_aquatica_var_aquatica.pdf"
  },
  {
    subjectType: "community",
    subjectKey: 10702,
    name: "Alvar",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Alvar.pdf"
  },
  {
    subjectType: "community",
    subjectKey: 10666,
    name: "Bog",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Bog.pdf"
  },
  {
    subjectType: "community",
    subjectKey: 10690,
    name: "Boreal Forest",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Boreal_Forest.pdf"
  },
  {
    subjectType: "community",
    subjectKey: 10713,
    name: "Bur Oak Plains",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Bur_Oak_Plains.pdf"
  },
  {
    subjectType: "community",
    subjectKey: 19006,
    name: "Coastal Fen",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Coastal_Fen.pdf"
  },
  {
    subjectType: "community",
    subjectKey: 10670,
    name: "Coastal Plain Marsh",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Coastal_Plain_Marsh.pdf"
  },
  {
    subjectType: "community",
    subjectKey: 10689,
    name: "Dry Northern Forest",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Dry_Northern_Forest.pdf"
  },
  {
    subjectType: "community",
    subjectKey: 10698,
    name: "Dry Sand Prairie",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Dry_Sand_Prairie.pdf"
  },
  {
    subjectType: "community",
    subjectKey: 10688,
    name: "Dry-mesic Northern Forest",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Dry-mesic_Northern_Forest.pdf"
  },
  {
    subjectType: "community",
    subjectKey: 10708,
    name: "Dry-mesic Prairie",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Dry-mesic_Prairie.pdf"
  },
  {
    subjectType: "community",
    subjectKey: 10685,
    name: "Dry-mesic Southern Forest",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Dry-Mesic_Southern_Forest.pdf"
  },
  {
    subjectType: "community",
    subjectKey: 10658,
    name: "Floodplain Forest",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Floodplain_Forest.pdf"
  },
  {
    subjectType: "community",
    subjectKey: 15989,
    name: "Granite Bedrock Lakeshore",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Granite_Bedrock_Lakeshore.pdf"
  },
  {
    subjectType: "community",
    subjectKey: 10671,
    name: "Great Lakes Marsh",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Great_Lakes_Marsh.pdf"
  },
  {
    subjectType: "community",
    subjectKey: 10656,
    name: "Hardwood-Conifer Swamp",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Hardwood-Conifer_Swamp.pdf"
  },
  {
    subjectType: "community",
    subjectKey: 10664,
    name: "Inland Salt Marsh",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Inland_Salt_Marsh.pdf"
  },
  {
    subjectType: "community",
    subjectKey: 10668,
    name: "Interdunal Wetland",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Interdunal_Wetland.pdf"
  },
  {
    subjectType: "community",
    subjectKey: 10661,
    name: "Intermittent Wetland",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Intermittent_Wetland.pdf"
  },
  {
    subjectType: "community",
    subjectKey: 10680,
    name: "Inundated Shrub Swamp",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Inundated_Shrub_Swamp.pdf"
  },
  {
    subjectType: "community",
    subjectKey: 10710,
    name: "Lakeplain Oak Openings",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Lakeplain_Oak_Openings.pdf"
  },
  {
    subjectType: "community",
    subjectKey: 10672,
    name: "Lakeplain Wet Prairie",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Lakeplain_Wet_Prairie.pdf"
  },
  {
    subjectType: "community",
    subjectKey: 10675,
    name: "Lakeplain Wet-mesic Prairie",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Lakeplain_Wet-Mesic_Prairie.pdf"
  },
  {
    subjectType: "community",
    subjectKey: 15983,
    name: "Limestone Bedrock Glade",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Limestone_Bedrock_Glade.pdf"
  },
  {
    subjectType: "community",
    subjectKey: 10717,
    name: "Limestone Bedrock Lakeshore",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Limestone_Bedrock_Lakeshore.pdf"
  },
  {
    subjectType: "community",
    subjectKey: 18982,
    name: "Limestone Cobble Shore",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Limestone_Cobble_Shore.pdf"
  },
  {
    subjectType: "community",
    subjectKey: 10687,
    name: "Mesic Northern Forest",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Mesic_Northern_Forest.pdf"
  },
  {
    subjectType: "community",
    subjectKey: 10697,
    name: "Mesic Prairie",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Mesic_Prairie.pdf"
  },
  {
    subjectType: "community",
    subjectKey: 10696,
    name: "Mesic Sand Prairie",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Mesic_Sand_Prairie.pdf"
  },
  {
    subjectType: "community",
    subjectKey: 10684,
    name: "Mesic Southern Forest",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Mesic_Southern_Forest.pdf"
  },
  {
    subjectType: "community",
    subjectKey: 10678,
    name: "Muskeg",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Muskeg.pdf"
  },
  {
    subjectType: "community",
    subjectKey: 10673,
    name: "Northern Fen",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Northern_Fen.pdf"
  },
  {
    subjectType: "community",
    subjectKey: 10659,
    name: "Northern Hardwood Swamp",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Northern_Hardwood_Swamp.pdf"
  },
  {
    subjectType: "community",
    subjectKey: 10677,
    name: "Northern Shrub Thicket",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Northern_Shrub_Thicket.pdf"
  },
  {
    subjectType: "community",
    subjectKey: 10663,
    name: "Northern Wet Meadow",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Northern_Wet_Meadow.pdf"
  },
  {
    subjectType: "community",
    subjectKey: 10693,
    name: "Oak Barrens",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Oak_Barrens.pdf"
  },
  {
    subjectType: "community",
    subjectKey: 10691,
    name: "Oak Openings",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Oak_Openings.pdf"
  },
  {
    subjectType: "community",
    subjectKey: 10692,
    name: "Oak-Pine Barrens",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Oak-Pine_Barrens.pdf"
  },
  {
    subjectType: "community",
    subjectKey: 10699,
    name: "Open Dunes",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Open_Dunes.pdf"
  },
  {
    subjectType: "community",
    subjectKey: 10669,
    name: "Patterned Fen",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Patterned_Fen.pdf"
  },
  {
    subjectType: "community",
    subjectKey: 10694,
    name: "Pine Barrens",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Pine_Barrens.pdf"
  },
  {
    subjectType: "community",
    subjectKey: 10653,
    name: "Poor Conifer Swamp",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Poor_Conifer_Swamp.pdf"
  },
  {
    subjectType: "community",
    subjectKey: 10662,
    name: "Poor Fen",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Poor_Fen.pdf"
  },
  {
    subjectType: "community",
    subjectKey: 10667,
    name: "Prairie Fen",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Prairie_Fen.pdf"
  },
  {
    subjectType: "community",
    subjectKey: 10652,
    name: "Rich Conifer Swamp",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Rich_Conifer_Swamp.pdf"
  },
  {
    subjectType: "community",
    subjectKey: 10660,
    name: "Rich Tamarack Swamp",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Rich_Tamarack_Swamp.pdf"
  },
  {
    subjectType: "community",
    subjectKey: 10714,
    name: "Sand and Gravel Beach",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Sand_and_Gravel_Beach.pdf"
  },
  {
    subjectType: "community",
    subjectKey: 10719,
    name: "Sandstone Lakeshore Cliff",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Sandstone_Lakeshore_Cliff.pdf"
  },
  {
    subjectType: "community",
    subjectKey: 10655,
    name: "Southern Hardwood Swamp",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Southern_Hardwood_Swamp.pdf"
  },
  {
    subjectType: "community",
    subjectKey: 10657,
    name: "Southern Wet Meadow",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Southern_Wet_Meadow.pdf"
  },
  {
    subjectType: "community",
    subjectKey: 10715,
    name: "Volcanic Bedrock Glade",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Volcanic_Bedrock_Glade.pdf"
  },
  {
    subjectType: "community",
    subjectKey: 10716,
    name: "Volcanic Bedrock Lakeshore",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Volcanic_Bedrock_Lakeshore.pdf"
  },
  {
    subjectType: "community",
    subjectKey: 10665,
    name: "Wet Prairie",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Wet_Prairie.pdf"
  },
  {
    subjectType: "community",
    subjectKey: 19009,
    name: "Wet-mesic Flatwoods",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Wet-mesic_Flatwoods.pdf"
  },
  {
    subjectType: "community",
    subjectKey: 10674,
    name: "Wet-mesic Prairie",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Wet-mesic_Prairie.pdf"
  },
  {
    subjectType: "community",
    subjectKey: 10682,
    name: "Wet-mesic Sand Prairie",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Wet-Mesic_Sand_Prairie.pdf"
  },
  {
    subjectType: "community",
    subjectKey: 10679,
    name: "Wooded Dune and Swale Complex",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Wooded_Dune_and_Swale_Complex.pdf"
  },
  {
    subjectType: "other",
    subjectKey: null,
    name: "Great Blue Heron Rookery",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/zoology/Great_Blue_Heron_Rookery.pdf"
  },
  {
    subjectType: "other",
    subjectKey: null,
    name: "Vernal Pool",
    pdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Vernal_Pool.pdf"
  },
];
