// AUTO-GENERATED by lib/internal-data-providers/src/mnfi/scraper — do not edit manually.
// Scraped from https://mnfi.anr.msu.edu on 2026-06-29.

export interface SimilarCommunity {
  communityId: number;
  name: string;
}
export interface CommunitySimilar {
  communityId: number;
  similar: SimilarCommunity[];
}

export const MNFI_COMMUNITY_SIMILAR: CommunitySimilar[] = [
  {
    communityId: 10702,
    similar: [
    { communityId: 10717, name: "Limestone bedrock lakeshore" },
    { communityId: 15983, name: "limestone bedrock glade" },
    { communityId: 10690, name: "boreal forest" }
  ]
  },
  {
    communityId: 10666,
    similar: [
    { communityId: 10670, name: "Coastal plain marsh" },
    { communityId: 10661, name: "intermittent wetland" },
    { communityId: 10680, name: "inundated shrub swamp" },
    { communityId: 10678, name: "muskeg" },
    { communityId: 10673, name: "northern fen" },
    { communityId: 10669, name: "patterned fen" },
    { communityId: 10653, name: "poor conifer swamp" },
    { communityId: 10662, name: "poor fen" },
    { communityId: 10667, name: "prairie fen" },
    { communityId: 10660, name: "rich tamarack swamp" },
    { communityId: 10652, name: "rich conifer swamp" }
  ]
  },
  {
    communityId: 10690,
    similar: [
    { communityId: 10652, name: "Rich conifer swamp" },
    { communityId: 10687, name: "mesic northern forest" },
    { communityId: 10656, name: "hardwood-conifer swamp" },
    { communityId: 10688, name: "dry-mesic northern forest" },
    { communityId: 10712, name: "Great Lakes barrens" },
    { communityId: 15983, name: "limestone bedrock glade" },
    { communityId: 15978, name: "granite bedrock glade" },
    { communityId: 10715, name: "volcanic bedrock glade" },
    { communityId: 10679, name: "wooded dune and swale complex" }
  ]
  },
  {
    communityId: 10713,
    similar: [
    { communityId: 10710, name: "Lakeplain oak openings" },
    { communityId: 10697, name: "mesic prairie" },
    { communityId: 10693, name: "oak barrens" },
    { communityId: 10692, name: "oak-pine barrens" },
    { communityId: 10691, name: "oak openings" },
    { communityId: 10674, name: "wet-mesic prairie" }
  ]
  },
  {
    communityId: 10683,
    similar: [
    { communityId: 10707, name: "Sinkhole" }
  ]
  },
  {
    communityId: 19926,
    similar: [
    { communityId: 19006, name: "Coastal fen" },
    { communityId: 10677, name: "northern shrub thicket" },
    { communityId: 10699, name: "open dunes" }
  ]
  },
  {
    communityId: 19006,
    similar: [
    { communityId: 18982, name: "Limestone cobble shore" },
    { communityId: 10671, name: "Great Lakes marsh" },
    { communityId: 10667, name: "prairie fen" },
    { communityId: 10668, name: "interdunal wetland" },
    { communityId: 10673, name: "northern fen" },
    { communityId: 10652, name: "rich conifer swamp" },
    { communityId: 10679, name: "wooded dune and swale complex" }
  ]
  },
  {
    communityId: 10670,
    similar: [
    { communityId: 10661, name: "Intermittent wetland" },
    { communityId: 10682, name: "wet-mesic sand prairie" },
    { communityId: 10674, name: "wet-mesic prairie" }
  ]
  },
  {
    communityId: 10689,
    similar: [
    { communityId: 10694, name: "Pine barrens" },
    { communityId: 10688, name: "dry-mesic northern forest" },
    { communityId: 10692, name: "oak-pine barrens" },
    { communityId: 10679, name: "wooded dune and swale complex" }
  ]
  },
  {
    communityId: 10698,
    similar: [
    { communityId: 10708, name: "Dry-mesic prairie" },
    { communityId: 10709, name: "hillside prairie" },
    { communityId: 10693, name: "oak barrens" },
    { communityId: 10692, name: "oak-pine barrens" },
    { communityId: 10694, name: "pine barrens" }
  ]
  },
  {
    communityId: 10686,
    similar: [
    { communityId: 10693, name: "Oak barrens" },
    { communityId: 10692, name: "oak-pine barrens" },
    { communityId: 10685, name: "dry-mesic southern forest" },
    { communityId: 10689, name: "dry northern forest" },
    { communityId: 10688, name: "dry-mesic northern forest" }
  ]
  },
  {
    communityId: 10688,
    similar: [
    { communityId: 10689, name: "Dry northern forest" },
    { communityId: 10656, name: "hardwood-conifer swamp" },
    { communityId: 10687, name: "mesic northern forest" },
    { communityId: 10695, name: "northern bald" },
    { communityId: 15978, name: "granite bedrock glade" },
    { communityId: 10715, name: "volcanic bedrock glade" },
    { communityId: 10692, name: "oak-pine barrens" },
    { communityId: 10679, name: "wooded dune and swale complex" }
  ]
  },
  {
    communityId: 10708,
    similar: [
    { communityId: 10691, name: "Oak openings" },
    { communityId: 10698, name: "dry sand prairie" },
    { communityId: 10709, name: "hillside prairie" },
    { communityId: 10696, name: "mesic sand prairie" },
    { communityId: 10693, name: "oak barrens" },
    { communityId: 10713, name: "bur oak plains" },
    { communityId: 10697, name: "mesic prairie" }
  ]
  },
  {
    communityId: 10685,
    similar: [
    { communityId: 10686, name: "Dry southern forest" },
    { communityId: 10688, name: "dry-mesic northern forest" },
    { communityId: 10684, name: "mesic southern forest" },
    { communityId: 10691, name: "oak openings" }
  ]
  },
  {
    communityId: 10654,
    similar: [
    { communityId: 10651, name: "Submergent marsh" },
    { communityId: 10671, name: "Great Lakes marsh" },
    { communityId: 10661, name: "intermittent wetland" },
    { communityId: 10670, name: "coastal plain marsh" },
    { communityId: 10657, name: "southern wet meadow" },
    { communityId: 10663, name: "northern wet meadow" }
  ]
  },
  {
    communityId: 10658,
    similar: [
    { communityId: 10656, name: "Hardwood-conifer swamp" },
    { communityId: 10684, name: "mesic southern forest" },
    { communityId: 10687, name: "mesic northern forest" },
    { communityId: 10659, name: "northern hardwood swamp" },
    { communityId: 10655, name: "southern hardwood swamp" }
  ]
  },
  {
    communityId: 15978,
    similar: [
    { communityId: 10695, name: "Northern bald" },
    { communityId: 15989, name: "granite bedrock lakeshore" },
    { communityId: 10706, name: "granite cliff" },
    { communityId: 19003, name: "granite lakeshore cliff" },
    { communityId: 10715, name: "volcanic bedrock glade" },
    { communityId: 10716, name: "volcanic bedrock lakeshore" },
    { communityId: 19000, name: "volcanic cliff" },
    { communityId: 18988, name: "sandstone bedrock lakeshore" },
    { communityId: 18997, name: "sandstone cliff" },
    { communityId: 10688, name: "dry-mesic northern forest" }
  ]
  },
  {
    communityId: 15989,
    similar: [
    { communityId: 15978, name: "Granite bedrock glade" },
    { communityId: 10716, name: "volcanic bedrock lakeshore" },
    { communityId: 10723, name: "volcanic lakeshore cliff" },
    { communityId: 10715, name: "volcanic bedrock glade" },
    { communityId: 18988, name: "sandstone bedrock lakeshore" },
    { communityId: 10719, name: "sandstone lakeshore cliff" },
    { communityId: 10717, name: "limestone bedrock lakeshore" }
  ]
  },
  {
    communityId: 10706,
    similar: [
    { communityId: 19000, name: "Volcanic cliff" },
    { communityId: 10703, name: "limestone cliff" },
    { communityId: 18997, name: "sandstone cliff" },
    { communityId: 19003, name: "granite lakeshore cliff" },
    { communityId: 10723, name: "volcanic lakeshore cliff" },
    { communityId: 10719, name: "sandstone lakeshore cliff" },
    { communityId: 18991, name: "limestone lakeshore cliff" },
    { communityId: 15978, name: "granite bedrock glade" },
    { communityId: 10715, name: "volcanic bedrock glade" },
    { communityId: 10695, name: "northern bald" }
  ]
  },
  {
    communityId: 19003,
    similar: [
    { communityId: 10723, name: "Volcanic lakeshore cliff" },
    { communityId: 10719, name: "sandstone lakeshore cliff" },
    { communityId: 18991, name: "limestone lakeshore cliff" },
    { communityId: 10706, name: "granite cliff" },
    { communityId: 10703, name: "limestone cliff" },
    { communityId: 18997, name: "sandstone cliff" },
    { communityId: 19000, name: "volcanic cliff" },
    { communityId: 15978, name: "granite bedrock glade" },
    { communityId: 15989, name: "granite bedrock lakeshore" },
    { communityId: 10715, name: "volcanic bedrock glade" }
  ]
  },
  {
    communityId: 10712,
    similar: [
    { communityId: 10699, name: "Open dunes" },
    { communityId: 10668, name: "interdunal wetland" },
    { communityId: 10694, name: "pine barrens" },
    { communityId: 10692, name: "oak-pine barrens" }
  ]
  },
  {
    communityId: 10671,
    similar: [
    { communityId: 10651, name: "Submergent marsh" },
    { communityId: 10654, name: "emergent marsh" },
    { communityId: 10663, name: "northern wet meadow" },
    { communityId: 10657, name: "southern wet meadow" },
    { communityId: 10668, name: "interdunal wetland" },
    { communityId: 10662, name: "poor fen" },
    { communityId: 19006, name: "coastal fen" },
    { communityId: 10673, name: "northern fen" },
    { communityId: 10672, name: "lakeplain wet prairie" },
    { communityId: 10675, name: "lakeplain wet-mesic prairie" },
    { communityId: 10677, name: "northern shrub thicket" },
    { communityId: 10676, name: "southern shrub-carr" },
    { communityId: 10679, name: "wooded dune and swale complex" }
  ]
  },
  {
    communityId: 10656,
    similar: [
    { communityId: 10652, name: "Rich conifer swamp" },
    { communityId: 10660, name: "rich tamarack swamp" },
    { communityId: 10658, name: "floodplain forest" },
    { communityId: 10659, name: "northern hardwood swamp" },
    { communityId: 10655, name: "southern hardwood swamp" },
    { communityId: 10687, name: "mesic northern forest" }
  ]
  },
  {
    communityId: 10709,
    similar: [
    { communityId: 10698, name: "dry sand prairie" },
    { communityId: 10696, name: "mesic sand prairie" },
    { communityId: 10708, name: "dry-mesic prairie" },
    { communityId: 10697, name: "mesic prairie" },
    { communityId: 10693, name: "oak barrens" },
    { communityId: 10692, name: "oak-pine barrens" },
    { communityId: 10691, name: "oak openings" },
    { communityId: 10686, name: "dry southern forest" },
    { communityId: 10685, name: "dry-mesic southern forest" }
  ]
  },
  {
    communityId: 10664,
    similar: [
    { communityId: 10654, name: "Emergent marsh" }
  ]
  },
  {
    communityId: 10668,
    similar: [
    { communityId: 19006, name: "Coastal fen" },
    { communityId: 18982, name: "limestone cobble shore" },
    { communityId: 10673, name: "northern fen" },
    { communityId: 10667, name: "prairie fen" },
    { communityId: 10679, name: "wooded dune and swale complex" },
    { communityId: 10712, name: "Great Lakes barrens" }
  ]
  },
  {
    communityId: 10661,
    similar: [
    { communityId: 10666, name: "Bog" },
    { communityId: 10670, name: "coastal plain marsh" },
    { communityId: 10654, name: "emergent marsh" },
    { communityId: 10673, name: "northern fen" },
    { communityId: 10663, name: "northern wet meadow" },
    { communityId: 10662, name: "poor fen" }
  ]
  },
  {
    communityId: 10680,
    similar: [
    { communityId: 10654, name: "Emergent marsh" },
    { communityId: 10677, name: "northern shrub thicket" },
    { communityId: 10676, name: "southern shrub-carr" }
  ]
  },
  {
    communityId: 10710,
    similar: [
    { communityId: 10672, name: "Lakeplain wet prairie" },
    { communityId: 10675, name: "lakeplain wet-mesic prairie" },
    { communityId: 10682, name: "wet-mesic sand prairie" },
    { communityId: 10696, name: "mesic sand prairie" },
    { communityId: 19009, name: "wet-mesic flatwoods" },
    { communityId: 10713, name: "bur oak plains" },
    { communityId: 10691, name: "oak openings" },
    { communityId: 10685, name: "dry-mesic southern forest" },
    { communityId: 10698, name: "dry sand prairie" },
    { communityId: 10686, name: "dry southern forest" },
    { communityId: 10693, name: "oak barrens" },
    { communityId: 10692, name: "oak-pine barrens" },
    { communityId: 10679, name: "wooded dune and swale complex" }
  ]
  },
  {
    communityId: 10672,
    similar: [
    { communityId: 10675, name: "Lakeplain wet-mesic prairie" },
    { communityId: 10665, name: "wet prairie" },
    { communityId: 10674, name: "wet-mesic prairie" },
    { communityId: 10682, name: "wet-mesic sand prairie" },
    { communityId: 10657, name: "southern wet meadow" },
    { communityId: 10671, name: "Great Lakes marsh" },
    { communityId: 10654, name: "emergent marsh" }
  ]
  },
  {
    communityId: 10675,
    similar: [
    { communityId: 10672, name: "Lakeplain wet prairie" },
    { communityId: 10674, name: "wet-mesic prairie" },
    { communityId: 10682, name: "wet-mesic sand prairie" },
    { communityId: 10696, name: "mesic sand prairie" },
    { communityId: 10697, name: "mesic prairie" }
  ]
  },
  {
    communityId: 15983,
    similar: [
    { communityId: 10702, name: "Alvar" },
    { communityId: 10717, name: "limestone bedrock lakeshore" },
    { communityId: 18982, name: "limestone cobble shore" },
    { communityId: 18991, name: "limestone lakeshore cliff" },
    { communityId: 10703, name: "limestone cliff" },
    { communityId: 10690, name: "boreal forest" }
  ]
  },
  {
    communityId: 10717,
    similar: [
    { communityId: 18982, name: "Limestone cobble shore" },
    { communityId: 15983, name: "limestone bedrock glade" },
    { communityId: 10702, name: "alvar" },
    { communityId: 18988, name: "sandstone bedrock lakeshore" },
    { communityId: 10716, name: "volcanic bedrock lakeshore" },
    { communityId: 15989, name: "granite bedrock lakeshore" }
  ]
  },
  {
    communityId: 10703,
    similar: [
    { communityId: 18991, name: "Limestone lakeshore cliff" },
    { communityId: 18997, name: "sandstone cliff" },
    { communityId: 10719, name: "sandstone lakeshore cliff" },
    { communityId: 19000, name: "volcanic cliff" },
    { communityId: 10723, name: "volcanic lakeshore cliff" },
    { communityId: 10706, name: "granite cliff" },
    { communityId: 19003, name: "granite lakeshore cliff" },
    { communityId: 15983, name: "limestone bedrock glade" },
    { communityId: 10695, name: "northern bald" }
  ]
  },
  {
    communityId: 18982,
    similar: [
    { communityId: 10717, name: "Limestone bedrock lakeshore" },
    { communityId: 10714, name: "sand and gravel beach" },
    { communityId: 19006, name: "coastal fen" },
    { communityId: 18994, name: "volcanic cobble shore" },
    { communityId: 18985, name: "sandstone cobble shore" },
    { communityId: 10671, name: "Great Lakes marsh" }
  ]
  },
  {
    communityId: 18991,
    similar: [
    { communityId: 10703, name: "Limestone cliff" },
    { communityId: 10719, name: "sandstone lakeshore cliff" },
    { communityId: 10723, name: "volcanic lakeshore cliff" },
    { communityId: 19003, name: "granite lakeshore cliff" },
    { communityId: 10706, name: "granite cliff" },
    { communityId: 18997, name: "sandstone cliff" },
    { communityId: 15983, name: "limestone bedrock glade" },
    { communityId: 10717, name: "limestone bedrock lakeshore" },
    { communityId: 19000, name: "volcanic cliff" }
  ]
  },
  {
    communityId: 10687,
    similar: [
    { communityId: 10684, name: "Mesic southern forest" },
    { communityId: 10688, name: "dry-mesic northern forest" },
    { communityId: 10656, name: "hardwood-conifer swamp" }
  ]
  },
  {
    communityId: 10697,
    similar: [
    { communityId: 10708, name: "Dry-mesic prairie" },
    { communityId: 10713, name: "bur oak plains" },
    { communityId: 10691, name: "oak openings" },
    { communityId: 10696, name: "mesic sand prairie" }
  ]
  },
  {
    communityId: 10696,
    similar: [
    { communityId: 10682, name: "Wet-mesic sand prairie" },
    { communityId: 10708, name: "dry-mesic prairie" },
    { communityId: 10698, name: "dry sand prairie" },
    { communityId: 10697, name: "mesic prairie" },
    { communityId: 10675, name: "lakeplain wet-mesic prairie" }
  ]
  },
  {
    communityId: 10684,
    similar: [
    { communityId: 10687, name: "Mesic northern forest" },
    { communityId: 10685, name: "dry-mesic southern forest" },
    { communityId: 10655, name: "southern hardwood swamp" },
    { communityId: 10658, name: "floodplain forest" },
    { communityId: 19009, name: "wet-mesic flatwoods" }
  ]
  },
  {
    communityId: 10678,
    similar: [
    { communityId: 10666, name: "Bog" },
    { communityId: 10673, name: "northern fen" },
    { communityId: 10669, name: "patterned fen" },
    { communityId: 10662, name: "poor fen" },
    { communityId: 10653, name: "poor conifer swamp" },
    { communityId: 10660, name: "rich tamarack swamp" },
    { communityId: 10652, name: "rich conifer swamp" }
  ]
  },
  {
    communityId: 10695,
    similar: [
    { communityId: 15978, name: "Granite bedrock glade" },
    { communityId: 10715, name: "volcanic bedrock glade" },
    { communityId: 15983, name: "limestone bedrock glade" },
    { communityId: 10706, name: "granite cliff" },
    { communityId: 10703, name: "limestone cliff" },
    { communityId: 18997, name: "sandstone cliff" },
    { communityId: 19000, name: "volcanic cliff" }
  ]
  },
  {
    communityId: 10673,
    similar: [
    { communityId: 19006, name: "Coastal fen" },
    { communityId: 10671, name: "Great Lakes marsh" },
    { communityId: 10668, name: "interdunal wetland" },
    { communityId: 10661, name: "intermittent wetland" },
    { communityId: 10678, name: "muskeg" },
    { communityId: 10669, name: "patterned fen" },
    { communityId: 10662, name: "poor fen" },
    { communityId: 10667, name: "prairie fen" },
    { communityId: 10652, name: "rich conifer swamp" },
    { communityId: 10679, name: "wooded dune and swale complex" }
  ]
  },
  {
    communityId: 10659,
    similar: [
    { communityId: 10655, name: "Southern hardwood swamp" },
    { communityId: 10656, name: "hardwood-conifer swamp" },
    { communityId: 10677, name: "northern shrub thicket" },
    { communityId: 10658, name: "floodplain forest" }
  ]
  },
  {
    communityId: 10677,
    similar: [
    { communityId: 10658, name: "Floodplain forest" },
    { communityId: 10671, name: "Great Lakes marsh" },
    { communityId: 10656, name: "hardwood-conifer swamp" },
    { communityId: 10680, name: "inundated shrub swamp" },
    { communityId: 10673, name: "northern fen" },
    { communityId: 10659, name: "northern hardwood swamp" },
    { communityId: 10663, name: "northern wet meadow" },
    { communityId: 10653, name: "poor conifer swamp" },
    { communityId: 10652, name: "rich conifer swamp" },
    { communityId: 10676, name: "southern shrub-carr" },
    { communityId: 10679, name: "wooded dune and swale complex" }
  ]
  },
  {
    communityId: 10663,
    similar: [
    { communityId: 10654, name: "Emergent marsh" },
    { communityId: 10671, name: "Great Lakes marsh" },
    { communityId: 10661, name: "intermittent wetland" },
    { communityId: 10657, name: "southern wet meadow" },
    { communityId: 10673, name: "northern fen" },
    { communityId: 10677, name: "northern shrub thicket" },
    { communityId: 10682, name: "wet-mesic sand prairie" },
    { communityId: 10662, name: "poor fen" },
    { communityId: 10665, name: "wet prairie" }
  ]
  },
  {
    communityId: 10693,
    similar: [
    { communityId: 10713, name: "Bur oak plains" },
    { communityId: 10698, name: "dry sand prairie" },
    { communityId: 10708, name: "dry-mesic prairie" },
    { communityId: 10686, name: "dry southern forest" },
    { communityId: 10710, name: "lakeplain oak openings" },
    { communityId: 10691, name: "oak openings" },
    { communityId: 10692, name: "oak-pine barrens" },
    { communityId: 10694, name: "pine barrens" }
  ]
  },
  {
    communityId: 10691,
    similar: [
    { communityId: 10713, name: "Bur oak plains" },
    { communityId: 10685, name: "dry-mesic southern forest" },
    { communityId: 10710, name: "lakeplain oak openings" },
    { communityId: 10697, name: "mesic prairie" },
    { communityId: 10693, name: "oak barrens" },
    { communityId: 10692, name: "oak-pine barrens" },
    { communityId: 10708, name: "dry-mesic prairie" }
  ]
  },
  {
    communityId: 10692,
    similar: [
    { communityId: 10713, name: "Bur oak plains" },
    { communityId: 10698, name: "dry sand prairie" },
    { communityId: 10686, name: "dry southern forest" },
    { communityId: 10689, name: "dry northern forest" },
    { communityId: 10712, name: "Great Lakes barrens" },
    { communityId: 10710, name: "lakeplain oak openings" },
    { communityId: 10691, name: "oak openings" },
    { communityId: 10693, name: "oak barrens" },
    { communityId: 10694, name: "pine barrens" }
  ]
  },
  {
    communityId: 10699,
    similar: [
    { communityId: 10712, name: "Great Lakes barrens" },
    { communityId: 10694, name: "pine barrens" },
    { communityId: 10692, name: "oak-pine barrens" },
    { communityId: 10668, name: "interdunal wetland" },
    { communityId: 10714, name: "sand and gravel beach" },
    { communityId: 10679, name: "wooded dune and swale complex" },
    { communityId: 10698, name: "dry sand prairie" }
  ]
  },
  {
    communityId: 10669,
    similar: [
    { communityId: 10673, name: "Northern fen" },
    { communityId: 19006, name: "coastal fen" },
    { communityId: 10662, name: "poor fen" },
    { communityId: 10663, name: "northern wet meadow" },
    { communityId: 10677, name: "northern shrub thicket" },
    { communityId: 10678, name: "muskeg" },
    { communityId: 10652, name: "rich conifer swamp" },
    { communityId: 10653, name: "poor conifer swamp" }
  ]
  },
  {
    communityId: 10694,
    similar: [
    { communityId: 10698, name: "Dry sand prairie" },
    { communityId: 10689, name: "dry northern forest" },
    { communityId: 10712, name: "Great Lakes barrens" },
    { communityId: 10693, name: "oak barrens" },
    { communityId: 10692, name: "oak-pine barrens" }
  ]
  },
  {
    communityId: 10653,
    similar: [
    { communityId: 10666, name: "Bog" },
    { communityId: 10678, name: "muskeg" },
    { communityId: 10673, name: "northern fen" },
    { communityId: 10669, name: "patterned fen" },
    { communityId: 10662, name: "poor fen" },
    { communityId: 10660, name: "rich tamarack swamp" },
    { communityId: 10652, name: "rich conifer swamp" }
  ]
  },
  {
    communityId: 10662,
    similar: [
    { communityId: 10666, name: "Bog" },
    { communityId: 19006, name: "coastal fen" },
    { communityId: 10661, name: "intermittent wetland" },
    { communityId: 10678, name: "muskeg" },
    { communityId: 10673, name: "northern fen" },
    { communityId: 10663, name: "northern wet meadow" },
    { communityId: 10669, name: "patterned fen" },
    { communityId: 10653, name: "poor conifer swamp" },
    { communityId: 10667, name: "prairie fen" },
    { communityId: 10652, name: "rich conifer swamp" }
  ]
  },
  {
    communityId: 10667,
    similar: [
    { communityId: 10673, name: "Northern fen" },
    { communityId: 10657, name: "southern wet meadow" },
    { communityId: 10654, name: "emergent marsh" },
    { communityId: 19006, name: "coastal fen" },
    { communityId: 10662, name: "poor fen" },
    { communityId: 10676, name: "southern shrub-carr" },
    { communityId: 10665, name: "wet prairie" },
    { communityId: 10674, name: "wet-mesic prairie" },
    { communityId: 10660, name: "rich tamarack swamp" }
  ]
  },
  {
    communityId: 10652,
    similar: [
    { communityId: 10660, name: "Rich tamarack swamp" },
    { communityId: 10656, name: "hardwood-conifer swamp" },
    { communityId: 10653, name: "poor conifer swamp" },
    { communityId: 10659, name: "northern hardwood swamp" },
    { communityId: 10690, name: "boreal forest" },
    { communityId: 10679, name: "wooded dune and swale complex" }
  ]
  },
  {
    communityId: 10660,
    similar: [
    { communityId: 10652, name: "Rich conifer swamp" },
    { communityId: 10656, name: "hardwood-conifer swamp" },
    { communityId: 10655, name: "southern hardwood swamp" },
    { communityId: 10659, name: "northern hardwood swamp" },
    { communityId: 10653, name: "poor conifer swamp" },
    { communityId: 10667, name: "prairie fen" },
    { communityId: 10676, name: "southern shrub-carr" },
    { communityId: 10657, name: "southern wet meadow" }
  ]
  },
  {
    communityId: 10714,
    similar: [
    { communityId: 10699, name: "Open dunes" },
    { communityId: 18982, name: "limestone cobble shore" },
    { communityId: 18985, name: "sandstone cobble shore" },
    { communityId: 18994, name: "volcanic cobble shore" },
    { communityId: 10679, name: "wooded dune and swale complex" }
  ]
  },
  {
    communityId: 18988,
    similar: [
    { communityId: 10719, name: "Sandstone lakeshore cliff" },
    { communityId: 10716, name: "volcanic bedrock lakeshore" },
    { communityId: 15989, name: "granite bedrock lakeshore" },
    { communityId: 10717, name: "limestone bedrock lakeshore" },
    { communityId: 10715, name: "volcanic bedrock glade" },
    { communityId: 15978, name: "granite bedrock glade" },
    { communityId: 10723, name: "volcanic lakeshore cliff" }
  ]
  },
  {
    communityId: 18997,
    similar: [
    { communityId: 10706, name: "Granite cliff" },
    { communityId: 10703, name: "limestone cliff" },
    { communityId: 19000, name: "volcanic cliff" },
    { communityId: 10719, name: "sandstone lakeshore cliff" },
    { communityId: 19003, name: "granite lakeshore cliff" },
    { communityId: 18991, name: "limestone lakeshore cliff" },
    { communityId: 10723, name: "volcanic lakeshore cliff" },
    { communityId: 15978, name: "granite bedrock glade" },
    { communityId: 10715, name: "volcanic bedrock glade" },
    { communityId: 10695, name: "northern bald" }
  ]
  },
  {
    communityId: 18985,
    similar: [
    { communityId: 18994, name: "Volcanic cobble shore" },
    { communityId: 18982, name: "limestone cobble shore" },
    { communityId: 18988, name: "sandstone bedrock lakeshore" },
    { communityId: 10719, name: "sandstone lakeshore cliff" },
    { communityId: 10714, name: "sand and gravel beach" }
  ]
  },
  {
    communityId: 10719,
    similar: [
    { communityId: 10723, name: "Volcanic lakeshore cliff" },
    { communityId: 19003, name: "granite lakeshore cliff" },
    { communityId: 18991, name: "limestone lakeshore cliff" },
    { communityId: 10706, name: "granite cliff" },
    { communityId: 10703, name: "limestone cliff" },
    { communityId: 18997, name: "sandstone cliff" },
    { communityId: 19000, name: "volcanic cliff" },
    { communityId: 15978, name: "granite bedrock glade" },
    { communityId: 10715, name: "volcanic bedrock glade" },
    { communityId: 18988, name: "sandstone bedrock lakeshore" },
    { communityId: 18985, name: "sandstone cobble shore" }
  ]
  },
  {
    communityId: 10707,
    similar: [
    { communityId: 10683, name: "Cave" }
  ]
  },
  {
    communityId: 10655,
    similar: [
    { communityId: 10656, name: "Hardwood-conifer swamp" },
    { communityId: 10659, name: "northern hardwood swamp" },
    { communityId: 10658, name: "floodplain forest" },
    { communityId: 19009, name: "wet-mesic flatwoods" }
  ]
  },
  {
    communityId: 10676,
    similar: [
    { communityId: 10667, name: "Prairie fen" },
    { communityId: 10657, name: "southern wet meadow" },
    { communityId: 10677, name: "northern shrub thicket" },
    { communityId: 10680, name: "inundated shrub swamp" },
    { communityId: 10655, name: "southern hardwood swamp" },
    { communityId: 10660, name: "rich tamarack swamp" }
  ]
  },
  {
    communityId: 10657,
    similar: [
    { communityId: 10654, name: "Emergent marsh" },
    { communityId: 10663, name: "northern wet meadow" },
    { communityId: 10662, name: "poor fen" },
    { communityId: 10667, name: "prairie fen" },
    { communityId: 10665, name: "wet prairie" },
    { communityId: 10672, name: "lakeplain wet prairie" },
    { communityId: 10671, name: "Great Lakes marsh" },
    { communityId: 10676, name: "southern shrub-carr" }
  ]
  },
  {
    communityId: 10651,
    similar: [
    { communityId: 10654, name: "Emergent marsh" },
    { communityId: 10661, name: "intermittent wetland" },
    { communityId: 10671, name: "Great Lakes marsh" }
  ]
  },
  {
    communityId: 10715,
    similar: [
    { communityId: 10695, name: "Northern bald" },
    { communityId: 15978, name: "granite bedrock glade" },
    { communityId: 15983, name: "limestone bedrock glade" },
    { communityId: 10688, name: "dry-mesic northern forest" },
    { communityId: 10690, name: "boreal forest" },
    { communityId: 10716, name: "volcanic bedrock lakeshore" },
    { communityId: 15989, name: "granite bedrock lakeshore" }
  ]
  },
  {
    communityId: 10716,
    similar: [
    { communityId: 15989, name: "Granite bedrock lakeshore" },
    { communityId: 18988, name: "sandstone bedrock lakeshore" },
    { communityId: 10717, name: "limestone bedrock lakeshore" },
    { communityId: 18994, name: "volcanic cobble shore" },
    { communityId: 10715, name: "volcanic bedrock glade" },
    { communityId: 10723, name: "volcanic lakeshore cliff" },
    { communityId: 15978, name: "granite bedrock glade" }
  ]
  },
  {
    communityId: 19000,
    similar: [
    { communityId: 10706, name: "Granite cliff" },
    { communityId: 10703, name: "limestone cliff" },
    { communityId: 18997, name: "sandstone cliff" },
    { communityId: 15978, name: "granite bedrock glade" },
    { communityId: 10715, name: "volcanic bedrock glade" },
    { communityId: 10723, name: "volcanic lakeshore cliff" },
    { communityId: 10695, name: "northern bald" }
  ]
  },
  {
    communityId: 18994,
    similar: [
    { communityId: 18982, name: "Limestone cobble shore" },
    { communityId: 18985, name: "sandstone cobble shore" },
    { communityId: 10716, name: "volcanic bedrock lakeshore" },
    { communityId: 10715, name: "volcanic bedrock glade" },
    { communityId: 10714, name: "sand and gravel beach" }
  ]
  },
  {
    communityId: 10723,
    similar: [
    { communityId: 19003, name: "Granite lakeshore cliff" },
    { communityId: 10719, name: "sandstone lakeshore cliff" },
    { communityId: 18991, name: "limestone lakeshore cliff" },
    { communityId: 10706, name: "granite cliff" },
    { communityId: 10703, name: "limestone cliff" },
    { communityId: 18997, name: "sandstone cliff" },
    { communityId: 19000, name: "volcanic cliff" },
    { communityId: 10715, name: "volcanic bedrock glade" },
    { communityId: 15978, name: "granite bedrock glade" },
    { communityId: 10716, name: "volcanic bedrock lakeshore" },
    { communityId: 10695, name: "northern bald" }
  ]
  },
  {
    communityId: 10665,
    similar: [
    { communityId: 10674, name: "Wet-mesic prairie" },
    { communityId: 10672, name: "lakeplain wet prairie" },
    { communityId: 10675, name: "lakeplain wet-mesic prairie" },
    { communityId: 10682, name: "wet-mesic sand prairie" },
    { communityId: 10657, name: "southern wet meadow" }
  ]
  },
  {
    communityId: 19009,
    similar: [
    { communityId: 10684, name: "Mesic southern forest" },
    { communityId: 10655, name: "southern hardwood swamp" },
    { communityId: 10710, name: "lakeplain oak openings" },
    { communityId: 10658, name: "floodplain forest" },
    { communityId: 10659, name: "northern hardwood swamp" }
  ]
  },
  {
    communityId: 10674,
    similar: [
    { communityId: 10665, name: "Wet prairie" },
    { communityId: 10682, name: "wet-mesic sand prairie" },
    { communityId: 10675, name: "lakeplain wet-mesic prairie" },
    { communityId: 10672, name: "lakeplain wet prairie" },
    { communityId: 10657, name: "southern wet meadow" },
    { communityId: 10667, name: "prairie fen" }
  ]
  },
  {
    communityId: 10682,
    similar: [
    { communityId: 10696, name: "Mesic sand prairie" },
    { communityId: 10674, name: "wet-mesic prairie" },
    { communityId: 10665, name: "wet prairie" },
    { communityId: 10675, name: "lakeplain wet-mesic prairie" },
    { communityId: 10672, name: "lakeplain wet prairie" }
  ]
  },
  {
    communityId: 10679,
    similar: [
    { communityId: 10654, name: "emergent marsh" },
    { communityId: 10663, name: "northern wet meadow" },
    { communityId: 10677, name: "northern shrub thicket" },
    { communityId: 10673, name: "northern fen" },
    { communityId: 10662, name: "poor fen" },
    { communityId: 19006, name: "coastal fen" },
    { communityId: 10712, name: "Great Lakes barrens" },
    { communityId: 10668, name: "interdunal wetland" },
    { communityId: 10652, name: "rich conifer swamp" },
    { communityId: 10653, name: "poor conifer swamp" },
    { communityId: 10656, name: "hardwood-conifer swamp" },
    { communityId: 10666, name: "bog" },
    { communityId: 10689, name: "dry northern forest" },
    { communityId: 10688, name: "dry-mesic northern forest" },
    { communityId: 10687, name: "mesic northern forest" },
    { communityId: 10699, name: "open dunes" },
    { communityId: 10714, name: "sand and gravel beach" }
  ]
  },
];
