// AUTO-GENERATED by lib/internal-data-providers/src/mnfi/scraper — do not edit manually.
// Scraped from https://mnfi.anr.msu.edu on 2026-06-29.

export interface CommunityStub {
  communityId: number;
  slug: string;
  name: string;
  communityClass: string;
  communityGroup: string;
  globalRank: string | null;
  stateRank: string | null;
}

export const MNFI_COMMUNITIES: CommunityStub[] = [
  {
    communityId: 10702,
    slug: "alvar",
    name: "Alvar",
    communityClass: "Primary Class",
    communityGroup: "Bedrock Grassland Group",
    globalRank: "G2?",
    stateRank: "S1"
  },
  {
    communityId: 10666,
    slug: "bog",
    name: "Bog",
    communityClass: "Palustrine Class",
    communityGroup: "Bog Group",
    globalRank: "G3G5",
    stateRank: "S4"
  },
  {
    communityId: 10690,
    slug: "boreal-forest",
    name: "Boreal Forest",
    communityClass: "Terrestrial Class",
    communityGroup: "Forest Group",
    globalRank: "GU",
    stateRank: "S3"
  },
  {
    communityId: 10713,
    slug: "bur-oak-plains",
    name: "Bur Oak Plains",
    communityClass: "Terrestrial Class",
    communityGroup: "Savanna Group",
    globalRank: "G1SX",
    stateRank: "SX"
  },
  {
    communityId: 10683,
    slug: "cave",
    name: "Cave",
    communityClass: "Subterranean/Sink Class",
    communityGroup: "Karst Group",
    globalRank: "G4?",
    stateRank: "S1"
  },
  {
    communityId: 19926,
    slug: "clay-bluff",
    name: "Clay Bluff",
    communityClass: "Primary Class",
    communityGroup: "Lakeshore Cliff/Bluff Group",
    globalRank: "GNR",
    stateRank: "S2"
  },
  {
    communityId: 19006,
    slug: "coastal-fen",
    name: "Coastal Fen",
    communityClass: "Palustrine Class",
    communityGroup: "Fen Group",
    globalRank: "G1G2",
    stateRank: "S2"
  },
  {
    communityId: 10670,
    slug: "coastal-plain-marsh",
    name: "Coastal Plain Marsh",
    communityClass: "Palustrine Class",
    communityGroup: "Marsh Group",
    globalRank: "G2",
    stateRank: "S2"
  },
  {
    communityId: 10689,
    slug: "dry-northern-forest",
    name: "Dry Northern Forest",
    communityClass: "Terrestrial Class",
    communityGroup: "Forest Group",
    globalRank: "G3?",
    stateRank: "S3"
  },
  {
    communityId: 10698,
    slug: "dry-sand-prairie",
    name: "Dry Sand Prairie",
    communityClass: "Terrestrial Class",
    communityGroup: "Prairie Group",
    globalRank: "G3",
    stateRank: "S2"
  },
  {
    communityId: 10686,
    slug: "dry-southern-forest",
    name: "Dry Southern Forest",
    communityClass: "Terrestrial Class",
    communityGroup: "Forest Group",
    globalRank: "G4",
    stateRank: "S3"
  },
  {
    communityId: 10688,
    slug: "dry-mesic-northern-forest",
    name: "Dry-mesic Northern Forest",
    communityClass: "Terrestrial Class",
    communityGroup: "Forest Group",
    globalRank: "G4",
    stateRank: "S3"
  },
  {
    communityId: 10708,
    slug: "dry-mesic-prairie",
    name: "Dry-mesic Prairie",
    communityClass: "Terrestrial Class",
    communityGroup: "Prairie Group",
    globalRank: "G3",
    stateRank: "S1"
  },
  {
    communityId: 10685,
    slug: "dry-mesic-southern-forest",
    name: "Dry-mesic Southern Forest",
    communityClass: "Terrestrial Class",
    communityGroup: "Forest Group",
    globalRank: "G4",
    stateRank: "S3"
  },
  {
    communityId: 10654,
    slug: "emergent-marsh",
    name: "Emergent Marsh",
    communityClass: "Palustrine Class",
    communityGroup: "Marsh Group",
    globalRank: "GU",
    stateRank: "S4"
  },
  {
    communityId: 10658,
    slug: "floodplain-forest",
    name: "Floodplain Forest",
    communityClass: "Palustrine Class",
    communityGroup: "Forested Wetland Group",
    globalRank: "G3?",
    stateRank: "S3"
  },
  {
    communityId: 15978,
    slug: "granite-bedrock-glade",
    name: "Granite Bedrock Glade",
    communityClass: "Primary Class",
    communityGroup: "Bedrock Glade Group",
    globalRank: "G3G5",
    stateRank: "S2"
  },
  {
    communityId: 15989,
    slug: "granite-bedrock-lakeshore",
    name: "Granite Bedrock Lakeshore",
    communityClass: "Primary Class",
    communityGroup: "Bedrock Lakeshore Group",
    globalRank: "G4G5",
    stateRank: "S2"
  },
  {
    communityId: 10706,
    slug: "granite-cliff",
    name: "Granite Cliff",
    communityClass: "Primary Class",
    communityGroup: "Inland Cliff Group",
    globalRank: "G4G5",
    stateRank: "S2"
  },
  {
    communityId: 19003,
    slug: "granite-lakeshore-cliff",
    name: "Granite Lakeshore Cliff",
    communityClass: "Primary Class",
    communityGroup: "Lakeshore Cliff/Bluff Group",
    globalRank: "GU",
    stateRank: "S1"
  },
  {
    communityId: 10712,
    slug: "great-lakes-barrens",
    name: "Great Lakes Barrens",
    communityClass: "Primary Class",
    communityGroup: "Dunes Group",
    globalRank: "G3",
    stateRank: "S2"
  },
  {
    communityId: 10671,
    slug: "great-lakes-marsh",
    name: "Great Lakes Marsh",
    communityClass: "Palustrine Class",
    communityGroup: "Marsh Group",
    globalRank: "G2",
    stateRank: "S3"
  },
  {
    communityId: 10656,
    slug: "hardwood-conifer-swamp",
    name: "Hardwood-Conifer Swamp",
    communityClass: "Palustrine Class",
    communityGroup: "Forested Wetland Group",
    globalRank: "G4",
    stateRank: "S3"
  },
  {
    communityId: 10709,
    slug: "hillside-prairie",
    name: "Hillside Prairie",
    communityClass: "Terrestrial Class",
    communityGroup: "Prairie Group",
    globalRank: "G3",
    stateRank: "S1"
  },
  {
    communityId: 10664,
    slug: "inland-salt-marsh",
    name: "Inland Salt Marsh",
    communityClass: "Palustrine Class",
    communityGroup: "Marsh Group",
    globalRank: "G1",
    stateRank: "S1"
  },
  {
    communityId: 10668,
    slug: "interdunal-wetland",
    name: "Interdunal Wetland",
    communityClass: "Palustrine Class",
    communityGroup: "Marsh Group",
    globalRank: "G2?",
    stateRank: "S2"
  },
  {
    communityId: 10661,
    slug: "intermittent-wetland",
    name: "Intermittent Wetland",
    communityClass: "Palustrine Class",
    communityGroup: "Marsh Group",
    globalRank: "G2",
    stateRank: "S3"
  },
  {
    communityId: 10680,
    slug: "inundated-shrub-swamp",
    name: "Inundated Shrub Swamp",
    communityClass: "Palustrine Class",
    communityGroup: "Shrub Wetland Group",
    globalRank: "G4",
    stateRank: "S3"
  },
  {
    communityId: 10710,
    slug: "lakeplain-oak-openings",
    name: "Lakeplain Oak Openings",
    communityClass: "Terrestrial Class",
    communityGroup: "Savanna Group",
    globalRank: "G2?",
    stateRank: "S1"
  },
  {
    communityId: 10672,
    slug: "lakeplain-wet-prairie",
    name: "Lakeplain Wet Prairie",
    communityClass: "Palustrine Class",
    communityGroup: "Wet Prairie Group",
    globalRank: "G2",
    stateRank: "S1"
  },
  {
    communityId: 10675,
    slug: "lakeplain-wet-mesic-prairie",
    name: "Lakeplain Wet-mesic Prairie",
    communityClass: "Palustrine Class",
    communityGroup: "Wet Prairie Group",
    globalRank: "G1?",
    stateRank: "S1"
  },
  {
    communityId: 15983,
    slug: "limestone-bedrock-glade",
    name: "Limestone Bedrock Glade",
    communityClass: "Primary Class",
    communityGroup: "Bedrock Glade Group",
    globalRank: "G2G4",
    stateRank: "S2"
  },
  {
    communityId: 10717,
    slug: "limestone-bedrock-lakeshore",
    name: "Limestone Bedrock Lakeshore",
    communityClass: "Primary Class",
    communityGroup: "Bedrock Lakeshore Group",
    globalRank: "G3",
    stateRank: "S2"
  },
  {
    communityId: 10703,
    slug: "limestone-cliff",
    name: "Limestone Cliff",
    communityClass: "Primary Class",
    communityGroup: "Inland Cliff Group",
    globalRank: "G4G5",
    stateRank: "S2"
  },
  {
    communityId: 18982,
    slug: "limestone-cobble-shore",
    name: "Limestone Cobble Shore",
    communityClass: "Primary Class",
    communityGroup: "Sand/Cobble Shore Group",
    globalRank: "G2G3",
    stateRank: "S3"
  },
  {
    communityId: 18991,
    slug: "limestone-lakeshore-cliff",
    name: "Limestone Lakeshore Cliff",
    communityClass: "Primary Class",
    communityGroup: "Lakeshore Cliff/Bluff Group",
    globalRank: "G4G5",
    stateRank: "S1"
  },
  {
    communityId: 10687,
    slug: "mesic-northern-forest",
    name: "Mesic Northern Forest",
    communityClass: "Terrestrial Class",
    communityGroup: "Forest Group",
    globalRank: "G4",
    stateRank: "S3"
  },
  {
    communityId: 10697,
    slug: "mesic-prairie",
    name: "Mesic Prairie",
    communityClass: "Terrestrial Class",
    communityGroup: "Prairie Group",
    globalRank: "G2",
    stateRank: "S1"
  },
  {
    communityId: 10696,
    slug: "mesic-sand-prairie",
    name: "Mesic Sand Prairie",
    communityClass: "Terrestrial Class",
    communityGroup: "Prairie Group",
    globalRank: "G2",
    stateRank: "S1"
  },
  {
    communityId: 10684,
    slug: "mesic-southern-forest",
    name: "Mesic Southern Forest",
    communityClass: "Terrestrial Class",
    communityGroup: "Forest Group",
    globalRank: "G2G3",
    stateRank: "S3"
  },
  {
    communityId: 10678,
    slug: "muskeg",
    name: "Muskeg",
    communityClass: "Palustrine Class",
    communityGroup: "Bog Group",
    globalRank: "G4G5",
    stateRank: "S3"
  },
  {
    communityId: 10695,
    slug: "northern-bald",
    name: "Northern Bald",
    communityClass: "Primary Class",
    communityGroup: "Bedrock Glade Group",
    globalRank: "GU",
    stateRank: "S1"
  },
  {
    communityId: 10673,
    slug: "northern-fen",
    name: "Northern Fen",
    communityClass: "Palustrine Class",
    communityGroup: "Fen Group",
    globalRank: "G3",
    stateRank: "S3"
  },
  {
    communityId: 10659,
    slug: "northern-hardwood-swamp",
    name: "Northern Hardwood Swamp",
    communityClass: "Palustrine Class",
    communityGroup: "Forested Wetland Group",
    globalRank: "G4",
    stateRank: "S3"
  },
  {
    communityId: 10677,
    slug: "northern-shrub-thicket",
    name: "Northern Shrub Thicket",
    communityClass: "Palustrine Class",
    communityGroup: "Shrub Wetland Group",
    globalRank: "G4",
    stateRank: "S5"
  },
  {
    communityId: 10663,
    slug: "northern-wet-meadow",
    name: "Northern Wet Meadow",
    communityClass: "Palustrine Class",
    communityGroup: "Marsh Group",
    globalRank: "G4G5",
    stateRank: "S4"
  },
  {
    communityId: 10693,
    slug: "oak-barrens",
    name: "Oak Barrens",
    communityClass: "Terrestrial Class",
    communityGroup: "Savanna Group",
    globalRank: "G2?",
    stateRank: "S1"
  },
  {
    communityId: 10691,
    slug: "oak-openings",
    name: "Oak Openings",
    communityClass: "Terrestrial Class",
    communityGroup: "Savanna Group",
    globalRank: "G1",
    stateRank: "S1"
  },
  {
    communityId: 10692,
    slug: "oak-pine-barrens",
    name: "Oak-Pine Barrens",
    communityClass: "Terrestrial Class",
    communityGroup: "Savanna Group",
    globalRank: "G3",
    stateRank: "S2"
  },
  {
    communityId: 10699,
    slug: "open-dunes",
    name: "Open Dunes",
    communityClass: "Primary Class",
    communityGroup: "Dunes Group",
    globalRank: "G3",
    stateRank: "S3"
  },
  {
    communityId: 10669,
    slug: "patterned-fen",
    name: "Patterned Fen",
    communityClass: "Palustrine Class",
    communityGroup: "Fen Group",
    globalRank: "GU",
    stateRank: "S2"
  },
  {
    communityId: 10694,
    slug: "pine-barrens",
    name: "Pine Barrens",
    communityClass: "Terrestrial Class",
    communityGroup: "Savanna Group",
    globalRank: "G3",
    stateRank: "S2"
  },
  {
    communityId: 10653,
    slug: "poor-conifer-swamp",
    name: "Poor Conifer Swamp",
    communityClass: "Palustrine Class",
    communityGroup: "Forested Wetland Group",
    globalRank: "G4",
    stateRank: "S4"
  },
  {
    communityId: 10662,
    slug: "poor-fen",
    name: "Poor Fen",
    communityClass: "Palustrine Class",
    communityGroup: "Fen Group",
    globalRank: "G3",
    stateRank: "S3"
  },
  {
    communityId: 10667,
    slug: "prairie-fen",
    name: "Prairie Fen",
    communityClass: "Palustrine Class",
    communityGroup: "Fen Group",
    globalRank: "G3",
    stateRank: "S3"
  },
  {
    communityId: 10652,
    slug: "rich-conifer-swamp",
    name: "Rich Conifer Swamp",
    communityClass: "Palustrine Class",
    communityGroup: "Forested Wetland Group",
    globalRank: "G4",
    stateRank: "S3"
  },
  {
    communityId: 10660,
    slug: "rich-tamarack-swamp",
    name: "Rich Tamarack Swamp",
    communityClass: "Palustrine Class",
    communityGroup: "Forested Wetland Group",
    globalRank: "G4",
    stateRank: "S3"
  },
  {
    communityId: 10714,
    slug: "sand-and-gravel-beach",
    name: "Sand and Gravel Beach",
    communityClass: "Primary Class",
    communityGroup: "Sand/Cobble Shore Group",
    globalRank: "G3?",
    stateRank: "S3"
  },
  {
    communityId: 18988,
    slug: "sandstone-bedrock-lakeshore",
    name: "Sandstone Bedrock Lakeshore",
    communityClass: "Primary Class",
    communityGroup: "Bedrock Lakeshore Group",
    globalRank: "G4G5",
    stateRank: "S2"
  },
  {
    communityId: 18997,
    slug: "sandstone-cliff",
    name: "Sandstone Cliff",
    communityClass: "Primary Class",
    communityGroup: "Inland Cliff Group",
    globalRank: "G4G5",
    stateRank: "S2"
  },
  {
    communityId: 18985,
    slug: "sandstone-cobble-shore",
    name: "Sandstone Cobble Shore",
    communityClass: "Primary Class",
    communityGroup: "Sand/Cobble Shore Group",
    globalRank: "G2G3",
    stateRank: "S2"
  },
  {
    communityId: 10719,
    slug: "sandstone-lakeshore-cliff",
    name: "Sandstone Lakeshore Cliff",
    communityClass: "Primary Class",
    communityGroup: "Lakeshore Cliff/Bluff Group",
    globalRank: "G3",
    stateRank: "S2"
  },
  {
    communityId: 10707,
    slug: "sinkhole",
    name: "Sinkhole",
    communityClass: "Subterranean/Sink Class",
    communityGroup: "Karst Group",
    globalRank: "G3G5",
    stateRank: "S2"
  },
  {
    communityId: 10655,
    slug: "southern-hardwood-swamp",
    name: "Southern Hardwood Swamp",
    communityClass: "Palustrine Class",
    communityGroup: "Forested Wetland Group",
    globalRank: "G3",
    stateRank: "S3"
  },
  {
    communityId: 10676,
    slug: "southern-shrub-carr",
    name: "Southern Shrub-carr",
    communityClass: "Palustrine Class",
    communityGroup: "Shrub Wetland Group",
    globalRank: "GU",
    stateRank: "S4"
  },
  {
    communityId: 10657,
    slug: "southern-wet-meadow",
    name: "Southern Wet Meadow",
    communityClass: "Palustrine Class",
    communityGroup: "Marsh Group",
    globalRank: "G4?",
    stateRank: "S3"
  },
  {
    communityId: 10651,
    slug: "submergent-marsh",
    name: "Submergent Marsh",
    communityClass: "Palustrine Class",
    communityGroup: "Marsh Group",
    globalRank: "GU",
    stateRank: "S4"
  },
  {
    communityId: 10715,
    slug: "volcanic-bedrock-glade",
    name: "Volcanic Bedrock Glade",
    communityClass: "Primary Class",
    communityGroup: "Bedrock Glade Group",
    globalRank: "GU",
    stateRank: "S2"
  },
  {
    communityId: 10716,
    slug: "volcanic-bedrock-lakeshore",
    name: "Volcanic Bedrock Lakeshore",
    communityClass: "Primary Class",
    communityGroup: "Bedrock Lakeshore Group",
    globalRank: "G4G5",
    stateRank: "S2"
  },
  {
    communityId: 19000,
    slug: "volcanic-cliff",
    name: "Volcanic Cliff",
    communityClass: "Primary Class",
    communityGroup: "Inland Cliff Group",
    globalRank: "G4G5",
    stateRank: "S2"
  },
  {
    communityId: 18994,
    slug: "volcanic-cobble-shore",
    name: "Volcanic Cobble Shore",
    communityClass: "Primary Class",
    communityGroup: "Sand/Cobble Shore Group",
    globalRank: "G4G5",
    stateRank: "S3"
  },
  {
    communityId: 10723,
    slug: "volcanic-lakeshore-cliff",
    name: "Volcanic Lakeshore Cliff",
    communityClass: "Primary Class",
    communityGroup: "Lakeshore Cliff/Bluff Group",
    globalRank: "GU",
    stateRank: "S1"
  },
  {
    communityId: 10665,
    slug: "wet-prairie",
    name: "Wet Prairie",
    communityClass: "Palustrine Class",
    communityGroup: "Wet Prairie Group",
    globalRank: "G3",
    stateRank: "S1"
  },
  {
    communityId: 19009,
    slug: "wet-mesic-flatwoods",
    name: "Wet-mesic Flatwoods",
    communityClass: "Palustrine Class",
    communityGroup: "Forested Wetland Group",
    globalRank: "G2G3",
    stateRank: "S2"
  },
  {
    communityId: 10674,
    slug: "wet-mesic-prairie",
    name: "Wet-mesic Prairie",
    communityClass: "Palustrine Class",
    communityGroup: "Wet Prairie Group",
    globalRank: "G2",
    stateRank: "S1"
  },
  {
    communityId: 10682,
    slug: "wet-mesic-sand-prairie",
    name: "Wet-mesic Sand Prairie",
    communityClass: "Palustrine Class",
    communityGroup: "Wet Prairie Group",
    globalRank: "G2G3",
    stateRank: "S2"
  },
  {
    communityId: 10679,
    slug: "wooded-dune-and-swale-complex",
    name: "Wooded Dune and Swale Complex",
    communityClass: "Palustrine/Terrestrial Class",
    communityGroup: "Wooded Dune and Swale Group",
    globalRank: "G3",
    stateRank: "S3"
  },
];
