// AUTO-GENERATED by lib/internal-data-providers/src/mnfi/scraper — do not edit manually.
// Scraped from https://mnfi.anr.msu.edu on 2026-06-29.

export interface CommunityExtras {
  communityId: number;
  placesToVisit: string[];
  literature: string[];
  photoUrl: string | null;
  countyMapUrl: string | null;
  ecoregionMapUrl: string | null;
  abstractPdfUrl: string | null;
  mnfiUrl: string;
}

export const MNFI_COMMUNITY_EXTRAS: CommunityExtras[] = [
  {
    communityId: 10702,
    placesToVisit: [
    "Escanaba River, Escanaba State Forest Management Unit, Delta Co.",
    "Maxton Plains (Drummond Island), Sault Sainte Marie State Forest Management Unit and The Nature Conservancy (Maxton Plains Preserve), Chippewa Co."
  ],
    literature: [],
    photoUrl: null,
    countyMapUrl: "https://mnfi.anr.msu.edu/community-maps/County_10702.png",
    ecoregionMapUrl: "https://mnfi.anr.msu.edu/community-maps/Alvar_Ecoregion_Map.pdf",
    abstractPdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Alvar.pdf",
    mnfiUrl: "https://mnfi.anr.msu.edu/communities/description/10702/alvar"
  },
  {
    communityId: 10666,
    placesToVisit: [
    "Green Road Bogs, Manistee National Forest, Mason Co.",
    "Long Lake, Traverse City State Forest Management Unit, Grand Traverse Co.",
    "Minden Bog, Minden City State Game Area, Sanilac Co.",
    "Miner Lake or Fennville Bog, Allegan State Game Area, Allegan Co.",
    "Purgatory Bog, Three Rivers State Game Area, St. Joseph Co.",
    "Race Road Bog, Waterloo State Recreation Area, Jackson Co.",
    "Richmond Lake, Manistee National Forest, Newaygo Co.",
    "Saul Lake Bog Nature Preserve, Land Conservancy of West Michigan, Kent Co.",
    "Stuart Lake, The Nature Conservancy (McMahon Lake Preserve), Luce Co.",
    "Sylvania Bogs, Sylvania Wilderness and Recreation Area, Ottawa National Forest, Gogebic Co.",
    "West Lake Bog and Bishop's Bog Preserve, City of Portage, Kalamazoo Co."
  ],
    literature: [],
    photoUrl: null,
    countyMapUrl: "https://mnfi.anr.msu.edu/community-maps/County_10666.png",
    ecoregionMapUrl: "https://mnfi.anr.msu.edu/community-maps/Bog_Ecoregion_Map.pdf",
    abstractPdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Bog.pdf",
    mnfiUrl: "https://mnfi.anr.msu.edu/communities/description/10666/bog"
  },
  {
    communityId: 10690,
    placesToVisit: [
    "Cap's Cabin and Waugoshance Point, Wilderness State Park, Emmet Co.",
    "Isle Royale National Park, Keweenaw Co.",
    "Keweenaw Point, Baraga State Forest Management Unit, Keweenaw Co.",
    "Lighthouse Point Boreal Forest (Bois Blanc Island), Gaylord State Forest Management Unit, Mackinac Co.",
    "Point Betsie, The Nature Conservancy (Zetterberg Preserve at Point Betsie), Benzie Co."
  ],
    literature: [],
    photoUrl: null,
    countyMapUrl: "https://mnfi.anr.msu.edu/community-maps/County_10690.png",
    ecoregionMapUrl: "https://mnfi.anr.msu.edu/community-maps/Boreal_Forest_Ecoregion_Map.pdf",
    abstractPdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Boreal_Forest.pdf",
    mnfiUrl: "https://mnfi.anr.msu.edu/communities/description/10690/boreal-forest"
  },
  {
    communityId: 10713,
    placesToVisit: [
    "Extirpated."
  ],
    literature: [],
    photoUrl: null,
    countyMapUrl: "https://mnfi.anr.msu.edu/community-maps/County_10713.png",
    ecoregionMapUrl: "https://mnfi.anr.msu.edu/community-maps/Bur_Oak_Plains_Ecoregion_Map.pdf",
    abstractPdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Bur_Oak_Plains.pdf",
    mnfiUrl: "https://mnfi.anr.msu.edu/communities/description/10713/bur-oak-plains"
  },
  {
    communityId: 10683,
    placesToVisit: [
    "Hendrie River Water Cave, Sault Sainte Marie State Forest Management Unit and Michigan Karst Conservancy, Mackinac Co.",
    "Kochab Cave, Sault Sainte Marie State Forest Management Unit and Michigan Karst Conservancy, Mackinac Co.",
    "Quarry Cave, Michigan Karst Conservancy, Mackinac Co."
  ],
    literature: [],
    photoUrl: null,
    countyMapUrl: "https://mnfi.anr.msu.edu/community-maps/County_10683.png",
    ecoregionMapUrl: "https://mnfi.anr.msu.edu/community-maps/Cave_Ecoregion_Map.pdf",
    abstractPdfUrl: null,
    mnfiUrl: "https://mnfi.anr.msu.edu/communities/description/10683/cave"
  },
  {
    communityId: 19926,
    placesToVisit: [
    "Porcupine Mountains Clay Bluffs, Porcupine Mountains Wilderness State Park, Gogebic Co.",
    "North Manitou Island, Sleeping Bear Dunes National Lakeshore, Leelanau Co.",
    "Sleeping Bear Dunes, Sleeping Bear Dunes National Lakeshore, Leelanau Co.",
    "Wau-Ke-Na, William Erby Smith Preserve, Southwest Michigan Land Conservancy, Allegan Co."
  ],
    literature: [],
    photoUrl: null,
    countyMapUrl: "https://mnfi.anr.msu.edu/community-maps/County_19926.png",
    ecoregionMapUrl: "https://mnfi.anr.msu.edu/community-maps/Clay_Bluff_Ecoregion_Map.pdf",
    abstractPdfUrl: null,
    mnfiUrl: "https://mnfi.anr.msu.edu/communities/description/19926/clay-bluff"
  },
  {
    communityId: 19006,
    placesToVisit: [
    "El Cajon Bay and Misery Bay, Atlanta State Forest Management Unit, Alpena Co.",
    "Horseshoe Bay Grosse Point, Horseshoe Bay Wilderness Area, Hiawatha National Forest, Mackinac Co.",
    "Thompson's Harbor, Thompson's Harbor State Park, Presque Isle Co.",
    "Voight Bay, Little Traverse Conservancy (Aldo Leopold Preserve), Mackinac Co."
  ],
    literature: [],
    photoUrl: null,
    countyMapUrl: "https://mnfi.anr.msu.edu/community-maps/County_19006.png",
    ecoregionMapUrl: "https://mnfi.anr.msu.edu/community-maps/Coastal_Fen_Ecoregion_Map.pdf",
    abstractPdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Coastal_Fen.pdf",
    mnfiUrl: "https://mnfi.anr.msu.edu/communities/description/19006/coastal-fen"
  },
  {
    communityId: 10670,
    placesToVisit: [
    "115th Avenue Pond, Goose Lake, 36th Ave, Allegan State Game Area, Allegan Co.",
    "Hamilton Township Coastal Plain Marsh Nature Sanctuary, Michigan Nature",
    "Association, Van Buren Co.",
    "Little Robinson Lake Marshes, Manistee National Forest, Newaygo Co.",
    "Pine Island Marsh Candidate Research Natural Area, Manistee National Forest, Muskegon Co.",
    "Ross Coastal Plain Marsh Preserve, The Nature Conservancy, Van Buren Co."
  ],
    literature: [],
    photoUrl: null,
    countyMapUrl: "https://mnfi.anr.msu.edu/community-maps/County_10670.png",
    ecoregionMapUrl: "https://mnfi.anr.msu.edu/community-maps/Coastal_Plain_Marsh_Ecoregion_Map.pdf",
    abstractPdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Coastal_Plain_Marsh.pdf",
    mnfiUrl: "https://mnfi.anr.msu.edu/communities/description/10670/coastal-plain-marsh"
  },
  {
    communityId: 10689,
    placesToVisit: [
    "Barclay Lake Jack Pines, Newberry State Forest Management Unit, Luce Co.",
    "Clark Lake Pine Ridges, Tahquamenon Falls State Park, Chippewa Co. and Luce Co.",
    "Crawford Red Pines, Grayling Forest Management Unit, Crawford Co.",
    "Hartwick Pines, Hartwick Pines State Park, Crawford Co.",
    "Prison Camp Dry Northern Forest, Tahquamenon Falls State Park and Newberry State Forest Management Unit, Luce Co. and Chippewa Co.",
    "Roscommon Red Pines, Roscommon Forest Management Unit, Roscommon Co."
  ],
    literature: [],
    photoUrl: null,
    countyMapUrl: "https://mnfi.anr.msu.edu/community-maps/County_10689.png",
    ecoregionMapUrl: "https://mnfi.anr.msu.edu/community-maps/Dry_Northern_Forest_Ecoregion_Map.pdf",
    abstractPdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Dry_Northern_Forest.pdf",
    mnfiUrl: "https://mnfi.anr.msu.edu/communities/description/10689/dry-northern-forest"
  },
  {
    communityId: 10698,
    placesToVisit: [
    "Coolbough Natural Areas, Brooks Township, Newaygo Co.",
    "Indian Lake Southwest, Manistee National Forest, Newaygo Co.",
    "Newaygo Prairie Nature Sanctuary, Michigan Nature Association, Newaygo Co.",
    "Sischo Prairies, Manistee National Forest, Oceana Co.",
    "Shupac Lake, Grayling State Forest Management Unit, Crawford Co.",
    "Tussing Prairie, Manistee National Forest, Lake Co."
  ],
    literature: [],
    photoUrl: null,
    countyMapUrl: "https://mnfi.anr.msu.edu/community-maps/County_10698.png",
    ecoregionMapUrl: "https://mnfi.anr.msu.edu/community-maps/Dry_Sand_Prairie_Ecoregion_Map.pdf",
    abstractPdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Dry_Sand_Prairie.pdf",
    mnfiUrl: "https://mnfi.anr.msu.edu/communities/description/10698/dry-sand-prairie"
  },
  {
    communityId: 10686,
    placesToVisit: [
    "Bassett Lake Woods, Barry State Game Area, Barry Co.",
    "Crooked Lake Forest, Waterloo State Recreation Area, Jackson Co. and Washtenaw Co.",
    "Moeckel Road Woods, Waterloo State Recreation Area, Jackson Co."
  ],
    literature: [],
    photoUrl: null,
    countyMapUrl: "https://mnfi.anr.msu.edu/community-maps/County_10686.png",
    ecoregionMapUrl: "https://mnfi.anr.msu.edu/community-maps/Dry_Southern_Forest_Ecoregion_Map.pdf",
    abstractPdfUrl: null,
    mnfiUrl: "https://mnfi.anr.msu.edu/communities/description/10686/dry-southern-forest"
  },
  {
    communityId: 10688,
    placesToVisit: [
    "Estivant Pines Nature Sanctuary, Michigan Nature Association, Keweenaw Co.",
    "Hartwick Pines, Hartwick Pines State Park, Crawford Co.",
    "Nebo Trail, Wilderness State Park, Emmet Co.",
    "Swamp Lakes, Newberry State Forest Management Unit and The Nature Conservancy (Swamp Lakes Preserve), Luce Co.",
    "Turner Creek Forest, Barry State Game Area, Barry Co.",
    "Two-Hearted Lakes, The Nature Conservancy (Two-Hearted River Forest Preserve), Luce Co."
  ],
    literature: [],
    photoUrl: null,
    countyMapUrl: "https://mnfi.anr.msu.edu/community-maps/County_10688.png",
    ecoregionMapUrl: "https://mnfi.anr.msu.edu/community-maps/Dry-mesic_Northern_Forest_Ecoregion_Map.pdf",
    abstractPdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Dry-mesic_Northern_Forest.pdf",
    mnfiUrl: "https://mnfi.anr.msu.edu/communities/description/10688/dry-mesic-northern-forest"
  },
  {
    communityId: 10708,
    placesToVisit: [
    "Foster Prairie, City of Ann Arbor, Washtenaw Co.",
    "Sauk Indian Trail Plant Preserve, Michigan Nature Association, St. Joseph Co."
  ],
    literature: [],
    photoUrl: null,
    countyMapUrl: "https://mnfi.anr.msu.edu/community-maps/County_10708.png",
    ecoregionMapUrl: "https://mnfi.anr.msu.edu/community-maps/Dry-mesic_Prairie_Ecoregion_Map.pdf",
    abstractPdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Dry-mesic_Prairie.pdf",
    mnfiUrl: "https://mnfi.anr.msu.edu/communities/description/10708/dry-mesic-prairie"
  },
  {
    communityId: 10685,
    placesToVisit: [
    "Aman Park, City of Grand Rapids, Ottawa Co.",
    "Forked Lake Woods and Mann Street Woods, Crane Pond State Game Area, Cass Co. Haven Hill, Highland State Recreation Area, Oakland Co.",
    "Norris Road Woods (Devil's Soupbowl) and Hall Lake, Yankee Springs State Recreation Area, Barry, Co.",
    "Pickerel Lake Complex, Pinckney State Recreation Area, Washtenaw Co.",
    "Seven Lakes, Seven Lakes State Park, Oakland Co.",
    "The Hills and Gun Lake Woods, Barry State Game Area, Barry Co."
  ],
    literature: [],
    photoUrl: null,
    countyMapUrl: "https://mnfi.anr.msu.edu/community-maps/County_10685.png",
    ecoregionMapUrl: "https://mnfi.anr.msu.edu/community-maps/Dry-mesic_Southern_Forest_Ecoregion_Map.pdf",
    abstractPdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Dry-Mesic_Southern_Forest.pdf",
    mnfiUrl: "https://mnfi.anr.msu.edu/communities/description/10685/dry-mesic-southern-forest"
  },
  {
    communityId: 10654,
    placesToVisit: [
    "Lake of the Clouds, Porcupine Mountains Wilderness State Park, Ontonagon Co.",
    "Moss Lake, Proud Lake State Recreation Area, Oakland Co.",
    "South Portage Marsh, Waterloo State Recreation Area, Jackson Co."
  ],
    literature: [],
    photoUrl: null,
    countyMapUrl: "https://mnfi.anr.msu.edu/community-maps/County_10654.png",
    ecoregionMapUrl: "https://mnfi.anr.msu.edu/community-maps/Emergent_Marsh_Ecoregion_Map.pdf",
    abstractPdfUrl: null,
    mnfiUrl: "https://mnfi.anr.msu.edu/communities/description/10654/emergent-marsh"
  },
  {
    communityId: 10658,
    placesToVisit: [
    "Aman Park, City of Grand Rapids, Ottawa Co.",
    "Big Daily Bayou, Allegan State Game Area, Allegan State Game Area, Allegan Co.",
    "Black River Floodplain Forest, Port Huron State Game Area, St. Clair Co.",
    "Haggerty Road Floodplain, Lower Huron Metropark, Wayne Co.",
    "Manistee River Floodplain, Manistee River State Game Area, Manistee Co.",
    "Maple River Floodplain, Maple River State Game Area, Clinton Co.",
    "Muskegon River, Gladwin State Forest Management Unit, Clare Co.",
    "Sturgeon River, Hiawatha National Forest, Delta Co.",
    "Warren Woods, Warren Woods State Park, Berrien Co.",
    "White River, Manistee National Forest, Oceana Co."
  ],
    literature: [],
    photoUrl: null,
    countyMapUrl: "https://mnfi.anr.msu.edu/community-maps/County_10658.png",
    ecoregionMapUrl: "https://mnfi.anr.msu.edu/community-maps/Floodplain_Forest_Ecoregion_Map.pdf",
    abstractPdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Floodplain_Forest.pdf",
    mnfiUrl: "https://mnfi.anr.msu.edu/communities/description/10658/floodplain-forest"
  },
  {
    communityId: 15978,
    placesToVisit: [
    "Lost Creek Outcrops, Gwinn State Forest Management Unit, Marquette Co.",
    "Lost Lake Outcrops, Crystal Falls State Forest Management Unit, Dickinson Co.",
    "Sugarloaf Glade, Gwinn State Forest Management Unit, Marquette Co.",
    "Van Riper Glades, Van Riper State Park, Marquette Co."
  ],
    literature: [],
    photoUrl: null,
    countyMapUrl: "https://mnfi.anr.msu.edu/community-maps/County_15978.png",
    ecoregionMapUrl: "https://mnfi.anr.msu.edu/community-maps/Granite_Bedrock_Glade_Ecoregion_Map.pdf",
    abstractPdfUrl: null,
    mnfiUrl: "https://mnfi.anr.msu.edu/communities/description/15978/granite-bedrock-glade"
  },
  {
    communityId: 15989,
    placesToVisit: [
    "Harvey, Gwinn State Forest Management Unit, Marquette Co.",
    "Little Presque Isle, Gwinn State Forest Management Unit, Marquette Co."
  ],
    literature: [],
    photoUrl: null,
    countyMapUrl: "https://mnfi.anr.msu.edu/community-maps/County_15989.png",
    ecoregionMapUrl: "https://mnfi.anr.msu.edu/community-maps/Granite_Bedrock_Lakeshore_Ecoregion_Map.pdf",
    abstractPdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Granite_Bedrock_Lakeshore.pdf",
    mnfiUrl: "https://mnfi.anr.msu.edu/communities/description/15989/granite-bedrock-lakeshore"
  },
  {
    communityId: 10706,
    placesToVisit: [
    "Lost Lake Outcrops, Crystal Falls State Forest Management Unit, Dickinson Co.",
    "Mulligan Cliffs, Gwinn State Forest Management Unit, Marquette Co.",
    "Van Riper Cliffs, Van Riper State Park, Marquette Co."
  ],
    literature: [],
    photoUrl: null,
    countyMapUrl: "https://mnfi.anr.msu.edu/community-maps/County_10706.png",
    ecoregionMapUrl: "https://mnfi.anr.msu.edu/community-maps/Granite_Cliff_Ecoregion_Map.pdf",
    abstractPdfUrl: null,
    mnfiUrl: "https://mnfi.anr.msu.edu/communities/description/10706/granite-cliff"
  },
  {
    communityId: 19003,
    placesToVisit: [
    "Little Presque Isle, Gwinn State Forest Management Unit, Marquette Co."
  ],
    literature: [],
    photoUrl: null,
    countyMapUrl: "https://mnfi.anr.msu.edu/community-maps/County_19003.png",
    ecoregionMapUrl: "https://mnfi.anr.msu.edu/community-maps/Granite_Lakeshore_Cliff_Ecoregion_Map.pdf",
    abstractPdfUrl: null,
    mnfiUrl: "https://mnfi.anr.msu.edu/communities/description/19003/granite-lakeshore-cliff"
  },
  {
    communityId: 10712,
    placesToVisit: [
    "Cathead Bay, Leelanau State Park, Leelanau Co.",
    "Nordhouse Dunes, Ludington State Park and Manistee National Forest, Mason Co.",
    "Platte Bay, Sleeping Bear Dunes National Lakeshore, Benzie Co.",
    "Sturgeon Bay, Wilderness State Park, Emmett Co."
  ],
    literature: [],
    photoUrl: null,
    countyMapUrl: "https://mnfi.anr.msu.edu/community-maps/County_10712.png",
    ecoregionMapUrl: "https://mnfi.anr.msu.edu/community-maps/Great_Lakes_Barrens_Ecoregion_Map.pdf",
    abstractPdfUrl: null,
    mnfiUrl: "https://mnfi.anr.msu.edu/communities/description/10712/great-lakes-barrens"
  },
  {
    communityId: 10671,
    placesToVisit: [
    "Duncan Bay, Cheboygan State Park, Cheboygan Co.",
    "El Cajon Bay and Misery Bay, Atlanta State Forest Management Unit, Alpena Co.",
    "Munuscong River Mouth, Sault Sainte Marie State Forest Management Unit, Chippewa Co.",
    "Pinconning, Pinconning County Park, Bay Co.",
    "Pointe Aux Chenes, Hiawatha National Forest, Mackinac Co.",
    "Pottawattomie Bayou, Grand Haven Township Park, Ottawa Co.",
    "St. Martin Bay, Hiawatha National Forest, Mackinac Co.",
    "Waugoshance Point, Wilderness State Park, Emmet Co.",
    "Wildfowl Bay Islands, Wildfowl Bay Wildlife Area, Huron Co."
  ],
    literature: [],
    photoUrl: null,
    countyMapUrl: "https://mnfi.anr.msu.edu/community-maps/County_10671.png",
    ecoregionMapUrl: "https://mnfi.anr.msu.edu/community-maps/Great_Lakes_Marsh_Ecoregion_Map.pdf",
    abstractPdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Great_Lakes_Marsh.pdf",
    mnfiUrl: "https://mnfi.anr.msu.edu/communities/description/10671/great-lakes-marsh"
  },
  {
    communityId: 10656,
    placesToVisit: [
    "Beavertown Lakes, Newberry State Forest Management Unit and The Nature Conservancy (Two-Hearted River Forest Preserve), Luce Co.",
    "Clinton River Headwaters, Independence Oaks County Park, Oakland County Parks, Oakland Co.",
    "Long Lake, Yankee Springs State Recreation Area, Barry Co.",
    "Mill Creek Swamp, Three Rivers State Game Area, Cass Co. and St. Joseph Co.",
    "Tahquamenon River, Tahquamenon Falls State Park, Chippewa Co. and Luce Co."
  ],
    literature: [],
    photoUrl: null,
    countyMapUrl: "https://mnfi.anr.msu.edu/community-maps/County_10656.png",
    ecoregionMapUrl: "https://mnfi.anr.msu.edu/community-maps/Hardwood-Conifer_Swamp_Ecoregion_Map.pdf",
    abstractPdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Hardwood-Conifer_Swamp.pdf",
    mnfiUrl: "https://mnfi.anr.msu.edu/communities/description/10656/hardwood-conifer-swamp"
  },
  {
    communityId: 10709,
    placesToVisit: [
    "Pemene Falls, Escanaba State Forest Management Unit, Menominee Co.",
    "MacCready Reserve, Michigan State University, Jackson Co."
  ],
    literature: [],
    photoUrl: null,
    countyMapUrl: "https://mnfi.anr.msu.edu/community-maps/County_10709.png",
    ecoregionMapUrl: "https://mnfi.anr.msu.edu/community-maps/Hillside_Prairie_Ecoregion_Map.pdf",
    abstractPdfUrl: null,
    mnfiUrl: "https://mnfi.anr.msu.edu/communities/description/10709/hillside-prairie"
  },
  {
    communityId: 10664,
    placesToVisit: [
    "Maple River, Maple River State Game Area, Clinton Co."
  ],
    literature: [],
    photoUrl: null,
    countyMapUrl: "https://mnfi.anr.msu.edu/community-maps/County_10664.png",
    ecoregionMapUrl: "https://mnfi.anr.msu.edu/community-maps/Inland_Salt_Marsh_Ecoregion_Map.pdf",
    abstractPdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Inland_Salt_Marsh.pdf",
    mnfiUrl: "https://mnfi.anr.msu.edu/communities/description/10664/inland-salt-marsh"
  },
  {
    communityId: 10668,
    placesToVisit: [
    "Big Knob Campground, Sault Sainte Marie State Forest Management Unit, Mackinac Co.",
    "Muskegon Dunes, Muskegon State Park, Muskegon Co.",
    "Nordhouse Dunes, Ludington State Park and Manistee National Forest, Mason Co.",
    "Sturgeon Bay, Wilderness State Park, Emmett Co.",
    "Warren Dunes, Warren Dunes State Park, Berrien Co."
  ],
    literature: [],
    photoUrl: null,
    countyMapUrl: "https://mnfi.anr.msu.edu/community-maps/County_10668.png",
    ecoregionMapUrl: "https://mnfi.anr.msu.edu/community-maps/Interdunal_Wetland_Ecoregion_Map.pdf",
    abstractPdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Interdunal_Wetland.pdf",
    mnfiUrl: "https://mnfi.anr.msu.edu/communities/description/10668/interdunal-wetland"
  },
  {
    communityId: 10661,
    placesToVisit: [
    "Baraga Plains, Baraga Plains State Waterfowl Management Area, Baraga Co.",
    "Dagget Lake Wetlands and Norris Road Wetland, Barry State Game Area, Barry Co.",
    "Duck Lake, Atlanta State Forest Management Unit, Cheboygan Co.",
    "Frog Lakes, Grayling State Forest Management Unit, Crawford Co.",
    "Michaud Lake, Shingleton State Forest Management Unit, Schoolcraft Co.",
    "Swamp Lakes, Newberry State Forest Management Unit and The Nature Conservancy (Swamp Lakes Preserve), Luce Co."
  ],
    literature: [],
    photoUrl: null,
    countyMapUrl: "https://mnfi.anr.msu.edu/community-maps/County_10661.png",
    ecoregionMapUrl: "https://mnfi.anr.msu.edu/community-maps/Intermittent_Wetland_Ecoregion_Map.pdf",
    abstractPdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Intermittent_Wetland.pdf",
    mnfiUrl: "https://mnfi.anr.msu.edu/communities/description/10661/intermittent-wetland"
  },
  {
    communityId: 10680,
    placesToVisit: [
    "Black River Shrub Swamp, Port Huron State Game Area, St. Clair Co.",
    "Crane Pond State Game Area, Cass Co.",
    "Crooked Lake Shrub Swamp, Pinckney State Recreation Area, Washtenaw Co.",
    "Three Rivers State Game Area, Cass Co. and St. Joseph Co.",
    "Trout Lake, Bald Mountain State Recreation Area, Oakland Co."
  ],
    literature: [],
    photoUrl: null,
    countyMapUrl: "https://mnfi.anr.msu.edu/community-maps/County_10680.png",
    ecoregionMapUrl: "https://mnfi.anr.msu.edu/community-maps/Inundated_Shrub_Swamp_Ecoregion_Map.pdf",
    abstractPdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Inundated_Shrub_Swamp.pdf",
    mnfiUrl: "https://mnfi.anr.msu.edu/communities/description/10680/inundated-shrub-swamp"
  },
  {
    communityId: 10710,
    placesToVisit: [
    "Algonac, Algonac State Park, St. Clair Co.",
    "Dickinson Island, St. Clair Flats State Wildlife Area, St. Clair Co.",
    "Killarney Beach, Bay City State Recreation Area, Bay Co.",
    "Wildfowl Bay Islands, Wildfowl Bay Wildlife Area, Huron Co."
  ],
    literature: [],
    photoUrl: null,
    countyMapUrl: "https://mnfi.anr.msu.edu/community-maps/County_10710.png",
    ecoregionMapUrl: "https://mnfi.anr.msu.edu/community-maps/Lakeplain_Oak_Openings_Ecoregion_Map.pdf",
    abstractPdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Lakeplain_Oak_Openings.pdf",
    mnfiUrl: "https://mnfi.anr.msu.edu/communities/description/10710/lakeplain-oak-openings"
  },
  {
    communityId: 10672,
    placesToVisit: [
    "Killarney Beach, Bay City State Recreation Area, Bay Co.",
    "Sebewaing Bay, Fish Point State Game Area, Tuscola Co."
  ],
    literature: [],
    photoUrl: null,
    countyMapUrl: "https://mnfi.anr.msu.edu/community-maps/County_10672.png",
    ecoregionMapUrl: "https://mnfi.anr.msu.edu/community-maps/Lakeplain_Wet_Prairie_Ecoregion_Map.pdf",
    abstractPdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Lakeplain_Wet_Prairie.pdf",
    mnfiUrl: "https://mnfi.anr.msu.edu/communities/description/10672/lakeplain-wet-prairie"
  },
  {
    communityId: 10675,
    placesToVisit: [
    "Algonac, Algonac State Park, St. Clair Co.",
    "Grand Mere, Grand Mere State Park, Berrien Co.",
    "Harsen's Island, St. Clair Flats State Wildlife Area, St. Clair Co.",
    "Sebewaing Bay, Fish Point State Game Area, Tuscola Co.",
    "Thomas Prairie, Fish Point State Game Area, Tuscola Co."
  ],
    literature: [],
    photoUrl: null,
    countyMapUrl: "https://mnfi.anr.msu.edu/community-maps/County_10675.png",
    ecoregionMapUrl: "https://mnfi.anr.msu.edu/community-maps/Lakeplain_Wet-mesic_Prairie_Ecoregion_Map.pdf",
    abstractPdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Lakeplain_Wet-Mesic_Prairie.pdf",
    mnfiUrl: "https://mnfi.anr.msu.edu/communities/description/10675/lakeplain-wet-mesic-prairie"
  },
  {
    communityId: 15983,
    placesToVisit: [
    "East Lake Glade, Hiawatha National Forest, Chippewa Co.",
    "Kregg Bay Glade (Garden Peninsula), Shingleton State Forest Management Unit, Delta Co.",
    "Maxton Plains (Drummond Island), Sault Sainte Marie State Forest Management Unit and The Nature Conservancy (Maxton Plains Preserve), Chippewa Co.",
    "The Rock (Drummond Island), Sault Saint Marie State Forest Management Unit, Chippewa Co.",
    "Thompson's Harbor, Thompson's Harbor State Park, Presque Isle Co."
  ],
    literature: [],
    photoUrl: null,
    countyMapUrl: "https://mnfi.anr.msu.edu/community-maps/County_15983.png",
    ecoregionMapUrl: "https://mnfi.anr.msu.edu/community-maps/Limestone_Bedrock_Glade_Ecoregion_Map.pdf",
    abstractPdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Limestone_Bedrock_Glade.pdf",
    mnfiUrl: "https://mnfi.anr.msu.edu/communities/description/15983/limestone-bedrock-glade"
  },
  {
    communityId: 10717,
    placesToVisit: [
    "Drummond Island (Bass Cove, Huron Bay, Grand Marais Lake, and Seaman's Point), Sault Sainte Marie State Forest Management Unit, Chippewa Co.",
    "Fisherman's Island, Fisherman's Island State Park, Charlevoix Co.",
    "Point De Tour, Shingleton State Forest Management Unit, Delta Co."
  ],
    literature: [],
    photoUrl: null,
    countyMapUrl: "https://mnfi.anr.msu.edu/community-maps/County_10717.png",
    ecoregionMapUrl: "https://mnfi.anr.msu.edu/community-maps/Limestone_Bedrock_Lakeshore_Ecoregion_Map.pdf",
    abstractPdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Limestone_Bedrock_Lakeshore.pdf",
    mnfiUrl: "https://mnfi.anr.msu.edu/communities/description/10717/limestone-bedrock-lakeshore"
  },
  {
    communityId: 10703,
    placesToVisit: [
    "Marblehead (Drummond Island), Sault Sainte Marie State Forest Management Unit, Chippewa Co.",
    "Rock River Canyon, Hiawatha National Forest, Alger Co."
  ],
    literature: [],
    photoUrl: null,
    countyMapUrl: "https://mnfi.anr.msu.edu/community-maps/County_10703.png",
    ecoregionMapUrl: "https://mnfi.anr.msu.edu/community-maps/Limestone_Cliff_Ecoregion_Map.pdf",
    abstractPdfUrl: null,
    mnfiUrl: "https://mnfi.anr.msu.edu/communities/description/10703/limestone-cliff"
  },
  {
    communityId: 18982,
    placesToVisit: [
    "Horseshoe Bay Grosse Point, Horseshoe Bay Wilderness Area, Hiawatha National Forest, Mackinac Co.",
    "Seiner's Point, Sault Sainte Marie State Forest Management Unit, Mackinac Co.",
    "St. Martin Point, Hiawatha National Forest, Mackinac Co.",
    "Thompson's Harbor, Thompson's Harbor State Park, Presque Isle Co.",
    "Waugoshance Point, Wilderness State Park, Emmet Co."
  ],
    literature: [],
    photoUrl: null,
    countyMapUrl: "https://mnfi.anr.msu.edu/community-maps/County_18982.png",
    ecoregionMapUrl: "https://mnfi.anr.msu.edu/community-maps/Limestone_Cobble_Shore_Ecoregion_Map.pdf",
    abstractPdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Limestone_Cobble_Shore.pdf",
    mnfiUrl: "https://mnfi.anr.msu.edu/communities/description/18982/limestone-cobble-shore"
  },
  {
    communityId: 18991,
    placesToVisit: [
    "Burnt Bluff (Garden Peninsula), Fayette Historic State Park, Delta Co.",
    "Middle Bluff (Garden Peninsula), Shingleton State Forest Management Unit and Fayette Historic State Park, Delta Co.",
    "Poe Point (Drummond Island), Maxton Plains Preserve, The Nature Conservancy, Chippewa Co."
  ],
    literature: [],
    photoUrl: null,
    countyMapUrl: "https://mnfi.anr.msu.edu/community-maps/County_18991.png",
    ecoregionMapUrl: "https://mnfi.anr.msu.edu/community-maps/Limestone_Lakeshore_Cliff_Ecoregion_Map.pdf",
    abstractPdfUrl: null,
    mnfiUrl: "https://mnfi.anr.msu.edu/communities/description/18991/limestone-lakeshore-cliff"
  },
  {
    communityId: 10687,
    placesToVisit: [
    "Betsy Lake, Tahquamenon Falls State Park, Luce Co. and Chippewa Co.",
    "Lake Gogebic, Lake Gogebic State Park, Gogebic Co.",
    "McCormick Tract, McCormick Research Natural Area, Ottawa National Forest, Marquette Co.",
    "Murphy Lake Hemlocks, Murphy Lake State Game Area, Oakland Co.",
    "P. J. Hoffmaster State Park, Ottawa Co. and Muskegon Co.",
    "Pictured Rocks, Pictured Rocks National Lakeshore, Alger Co.",
    "Porcupine Mountains, Porcupine Mountains Wilderness State Park, Gogebic Co. and Ontonagon Co.",
    "Port Huron Mesic Northern Forest, Port Huron State Game Area, St. Clair Co.",
    "Sleeping Bear Dunes, Sleeping Bear Dunes National Lakeshore, Leelanau Co.",
    "Sylvania, Sylvania Wilderness and Recreation Area, Ottawa National Forest, Gogebic Co.",
    "Walloon Lake, Gaylord State Forest Management Unit, Charlevoix Co."
  ],
    literature: [],
    photoUrl: null,
    countyMapUrl: "https://mnfi.anr.msu.edu/community-maps/County_10687.png",
    ecoregionMapUrl: "https://mnfi.anr.msu.edu/community-maps/Mesic_Northern_Forest_Ecoregion_Map.pdf",
    abstractPdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Mesic_Northern_Forest.pdf",
    mnfiUrl: "https://mnfi.anr.msu.edu/communities/description/10687/mesic-northern-forest"
  },
  {
    communityId: 10697,
    placesToVisit: [
    "No remaining sites occur on lands accessible to the public. However, readers may be able to find remnants of mesic prairie along railroad tracks and adjacent to cemeteries in southwestern Michigan."
  ],
    literature: [],
    photoUrl: null,
    countyMapUrl: "https://mnfi.anr.msu.edu/community-maps/County_10697.png",
    ecoregionMapUrl: "https://mnfi.anr.msu.edu/community-maps/Mesic_Prairie_Ecoregion_Map.pdf",
    abstractPdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Mesic_Prairie.pdf",
    mnfiUrl: "https://mnfi.anr.msu.edu/communities/description/10697/mesic-prairie"
  },
  {
    communityId: 10696,
    placesToVisit: [
    "Minong Prairie, Petersburg State Game Area, Monroe Co.",
    "Pinckney Prairie, Pinckney State Recreation Area, Washtenaw Co.",
    "Teeple Lake, Highland State Recreation Area, Oakland Co."
  ],
    literature: [],
    photoUrl: null,
    countyMapUrl: "https://mnfi.anr.msu.edu/community-maps/County_10696.png",
    ecoregionMapUrl: "https://mnfi.anr.msu.edu/community-maps/Mesic_Sand_Prairie_Ecoregion_Map.pdf",
    abstractPdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Mesic_Sand_Prairie.pdf",
    mnfiUrl: "https://mnfi.anr.msu.edu/communities/description/10696/mesic-sand-prairie"
  },
  {
    communityId: 10684,
    placesToVisit: [
    "Baker Woodlot, Michigan State University, Ingham Co.",
    "Crane Hills, Crane Pond State Game Area, Cass Co.",
    "Grand Valley Ravines, Grand Valley State College, Ottawa Co.",
    "Haven Hill, Highland State Recreation Area, Oakland Co.",
    "Russ Forest, Michigan State University, Cass Co.",
    "Sanford Woods, Michigan State University, Ingham Co.",
    "Sharon Hollow, The Nature Conservancy (Nan Weston Nature Preserve at Sharon Hollow, Washtenaw Co.",
    "Warren Dunes, Warren Dunes State Park, Berrien Co.",
    "Warren Woods, Warren Woods State Park, Berrien Co."
  ],
    literature: [],
    photoUrl: null,
    countyMapUrl: "https://mnfi.anr.msu.edu/community-maps/County_10684.png",
    ecoregionMapUrl: "https://mnfi.anr.msu.edu/community-maps/Mesic_Southern_Forest_Ecoregion_Map.pdf",
    abstractPdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Mesic_Southern_Forest.pdf",
    mnfiUrl: "https://mnfi.anr.msu.edu/communities/description/10684/mesic-southern-forest"
  },
  {
    communityId: 10678,
    placesToVisit: [
    "Betchler Tamarack Flats Candidate Research Natural Area, Hiawatha National Forest, Chippewa Co.",
    "Dawson Creek Muskeg, Newberry State Forest Management Unit and The Nature Conservancy (Two-Hearted River Forest Preserve), Luce Co.",
    "Nine Mile Muskeg, Roscommon State Forest Management Unit, Roscommon Co.",
    "No Muskeg for Old Men, Newberry State Forest Management Unit, Luce Co.",
    "Prison Camp Muskeg, Tahquamenon Falls State Park and Newberry State Forest Management Unit, Luce Co. and Chippewa Co.",
    "Sylvania, Sylvania Wilderness and Recreation Area, Ottawa National Forest, Gogebic Co."
  ],
    literature: [],
    photoUrl: null,
    countyMapUrl: "https://mnfi.anr.msu.edu/community-maps/County_10678.png",
    ecoregionMapUrl: "https://mnfi.anr.msu.edu/community-maps/Muskeg_Ecoregion_Map.pdf",
    abstractPdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Muskeg.pdf",
    mnfiUrl: "https://mnfi.anr.msu.edu/communities/description/10678/muskeg"
  },
  {
    communityId: 10695,
    placesToVisit: [
    "Bare Bluffs Bald, Michigan Nature Association (Grinnell Memorial Sanctuary at Bare Bluff), Keweenaw Co.",
    "Escarpment Trail, Porcupine Mountains Wilderness State Park, Ontonagon Co.",
    "Isle Royale National Park, Keweenaw Co.",
    "Mt. Lookout, Brockaway Mountain Drive, Keweenaw Co."
  ],
    literature: [],
    photoUrl: null,
    countyMapUrl: "https://mnfi.anr.msu.edu/community-maps/County_10695.png",
    ecoregionMapUrl: "https://mnfi.anr.msu.edu/community-maps/Northern_Bald_Ecoregion_Map.pdf",
    abstractPdfUrl: null,
    mnfiUrl: "https://mnfi.anr.msu.edu/communities/description/10695/northern-bald"
  },
  {
    communityId: 10673,
    placesToVisit: [
    "Horseshoe Bay, Horseshoe Bay Wilderness Area, Hiawatha National Forest, Mackinac Co.",
    "Pintail Pond, Rifle River State Recreation Area, Ogemaw Co.",
    "Sand Lakes, Sand Lakes Quiet Area, Traverse City State Forest Management Unit, Grand Traverse Co.",
    "Summerby Fen, Hiawatha National Forest, Mackinac Co.",
    "Thompson's Harbor, Thompson's Harbor State Park, Presque Isle Co.",
    "Wiregrass Lake (Carney Fen Natural Area), Escanaba State Forest Management Unit, Menominee Co."
  ],
    literature: [],
    photoUrl: null,
    countyMapUrl: "https://mnfi.anr.msu.edu/community-maps/County_10673.png",
    ecoregionMapUrl: "https://mnfi.anr.msu.edu/community-maps/Northern_Fen_Ecoregion_Map.pdf",
    abstractPdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Northern_Fen.pdf",
    mnfiUrl: "https://mnfi.anr.msu.edu/communities/description/10673/northern-fen"
  },
  {
    communityId: 10659,
    placesToVisit: [
    "Bear Swamp, Manistee National Forest, Lake Co. and Mason Co.",
    "Hopper's Swamp, Manistee National Forest, Manistee Co. and Mason Co.",
    "Porcupine Mountains, Porcupine Mountains Wilderness State Park, Gogebic Co. and Ontonagon Co.",
    "Walloon Lake Swamp, Gaylord State Forest Management Unit, Charlevoix Co."
  ],
    literature: [],
    photoUrl: null,
    countyMapUrl: "https://mnfi.anr.msu.edu/community-maps/County_10659.png",
    ecoregionMapUrl: "https://mnfi.anr.msu.edu/community-maps/Northern_Hardwood_Swamp_Ecoregion_Map.pdf",
    abstractPdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Northern_Hardwood_Swamp.pdf",
    mnfiUrl: "https://mnfi.anr.msu.edu/communities/description/10659/northern-hardwood-swamp"
  },
  {
    communityId: 10677,
    placesToVisit: [
    "Au Sable River, Hartwick Pines State Park, Crawford Co.",
    "Carp River, Porcupine Mountains Wilderness State Park, Ontonagon Co.",
    "Laughing Whitefish River, Laughing Whitefish Falls State Park, Alger Co.",
    "Little Two-Hearted River, Tahquamenon Falls State Park, Luce Co."
  ],
    literature: [],
    photoUrl: null,
    countyMapUrl: "https://mnfi.anr.msu.edu/community-maps/County_10677.png",
    ecoregionMapUrl: "https://mnfi.anr.msu.edu/community-maps/Northern_Shrub_Thicket_Ecoregion_Map.pdf",
    abstractPdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Northern_Shrub_Thicket.pdf",
    mnfiUrl: "https://mnfi.anr.msu.edu/communities/description/10677/northern-shrub-thicket"
  },
  {
    communityId: 10663,
    placesToVisit: [
    "Cannon Creek, Grayling State Forest Management Unit, Kalkaska Co.",
    "Carp River and Lake of the Clouds, Porcupine Mountains Wilderness State Park, Ontonagon Co.",
    "Creighton Marsh, Shingleton State Forest Management Unit, Schoolcraft Co.",
    "Hudson Creek, Roscommon State Forest Management Unit, Roscommon Co.",
    "Lost Lake, Crystal Falls State Management Unit, Dickinson Co.",
    "Pesheke Meadows, Van Riper State Park, Marquette Co."
  ],
    literature: [],
    photoUrl: null,
    countyMapUrl: "https://mnfi.anr.msu.edu/community-maps/County_10663.png",
    ecoregionMapUrl: "https://mnfi.anr.msu.edu/community-maps/Northern_Wet_Meadow_Ecoregion_Map.pdf",
    abstractPdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Northern_Wet_Meadow.pdf",
    mnfiUrl: "https://mnfi.anr.msu.edu/communities/description/10663/northern-wet-meadow"
  },
  {
    communityId: 10693,
    placesToVisit: [
    "Huron River Barrens, Island Lake State Recreation Area, Livingston Co.",
    "Pickerel Lake Complex, Pinckney State Recreation Area, Washtenaw Co.",
    "Proud Lake Barrens, Proud Lake State Recreation Area, Oakland Co."
  ],
    literature: [],
    photoUrl: null,
    countyMapUrl: "https://mnfi.anr.msu.edu/community-maps/County_10693.png",
    ecoregionMapUrl: "https://mnfi.anr.msu.edu/community-maps/Oak_Barrens_Ecoregion_Map.pdf",
    abstractPdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Oak_Barrens.pdf",
    mnfiUrl: "https://mnfi.anr.msu.edu/communities/description/10693/oak-barrens"
  },
  {
    communityId: 10691,
    placesToVisit: [
    "No remaining sites occur on lands accessible to the public. However, readers may be able to find remnants of oak openings along railroad tracks and adjacent to cemeteries in southwestern Michigan."
  ],
    literature: [],
    photoUrl: null,
    countyMapUrl: "https://mnfi.anr.msu.edu/community-maps/County_10691.png",
    ecoregionMapUrl: "https://mnfi.anr.msu.edu/community-maps/Oak_Openings_Ecoregion_Map.pdf",
    abstractPdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Oak_Openings.pdf",
    mnfiUrl: "https://mnfi.anr.msu.edu/communities/description/10691/oak-openings"
  },
  {
    communityId: 10692,
    placesToVisit: [
    "Allegan Oak-Pine Barrens, Allegan State Game Area, Allegan Co.",
    "Shakey Lakes, Escanaba State Forest Management Unit, Menominee Co.",
    "Sleeper Barrens, Albert E. Sleeper State Park and Rush Lake State Game Area, Huron Co."
  ],
    literature: [],
    photoUrl: null,
    countyMapUrl: "https://mnfi.anr.msu.edu/community-maps/County_10692.png",
    ecoregionMapUrl: "https://mnfi.anr.msu.edu/community-maps/Oak-Pine_Barrens_Ecoregion_Map.pdf",
    abstractPdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Oak-Pine_Barrens.pdf",
    mnfiUrl: "https://mnfi.anr.msu.edu/communities/description/10692/oak-pine-barrens"
  },
  {
    communityId: 10699,
    placesToVisit: [
    "Grand Mere, Grand Mere State Park, Berrien Co.",
    "Grand Sable Dunes, Pictured Rocks National Lakeshore, Alger Co.",
    "Muskegon Dunes, Muskegon State Park, Muskegon Co.",
    "Nordhouse Dunes, Ludington State Park and Manistee National Forest, Mason Co.",
    "North Manitou Island, Sleeping Bear Dunes National Lakeshore, Leelanau Co.",
    "P. J. Hoffmaster State Park, Ottawa Co. and Muskegon Co.",
    "Point Betsie, The Nature Conservancy (Zetterberg Preserve at Point Betsie), Benzie Co.",
    "Pyramid Point, Sleeping Bear Dunes National Lakeshore, Leelanau Co.",
    "Saugatuck Dunes, Saugatuck Dunes State Park, Allegan Co.",
    "Sleeping Bear Dunes, Sleeping Bear Dunes National Lakeshore, Leelanau Co.",
    "South Manitou Island, Sleeping Bear Dunes National Lakeshore, Leelanau Co.",
    "Warren Dunes, Warren Dunes State Park, Berrien Co."
  ],
    literature: [],
    photoUrl: null,
    countyMapUrl: "https://mnfi.anr.msu.edu/community-maps/County_10699.png",
    ecoregionMapUrl: "https://mnfi.anr.msu.edu/community-maps/Open_Dunes_Ecoregion_Map.pdf",
    abstractPdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Open_Dunes.pdf",
    mnfiUrl: "https://mnfi.anr.msu.edu/communities/description/10699/open-dunes"
  },
  {
    communityId: 10669,
    placesToVisit: [
    "Black Creek (Tokar's Patterned Fen), Newberry State Forest Management Unit, Chippewa Co.",
    "Creighton Marsh, Shingleton State Forest Management Unit, Schoolcraft Co.",
    "Marsh Creek (Seney Strangmoor), Seney National Wildlife Refuge and Shingleton State Forest Management Unit, Schoolcraft Co.",
    "McMahon Lake, Newberry State Forest Management Unit and The Nature Conservancy (McMahon Lake Preserve), Luce Co.",
    "Park Patterned Peatland, Tahquamenon Falls State Park, Chippewa Co.",
    "Sleeper Lake, Newberry State Forest Management Unit and The Nature Conservancy (McMahon Lake Preserve), Luce Co."
  ],
    literature: [],
    photoUrl: null,
    countyMapUrl: "https://mnfi.anr.msu.edu/community-maps/County_10669.png",
    ecoregionMapUrl: "https://mnfi.anr.msu.edu/community-maps/Patterned_Fen_Ecoregion_Map.pdf",
    abstractPdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Patterned_Fen.pdf",
    mnfiUrl: "https://mnfi.anr.msu.edu/communities/description/10669/patterned-fen"
  },
  {
    communityId: 10694,
    placesToVisit: [
    "Baraga Plains, Baraga State Forest Management Unit, Baraga Co.",
    "Frog Lake Barrens, Grayling State Forest Management Unit, Crawford Co.",
    "Little Bear Lake Barrens, Gaylord State Forest Management Unit, Otsego Co.",
    "Shupac Lake Barrens, Grayling State Forest Management Unit, Crawford Co."
  ],
    literature: [],
    photoUrl: null,
    countyMapUrl: "https://mnfi.anr.msu.edu/community-maps/County_10694.png",
    ecoregionMapUrl: "https://mnfi.anr.msu.edu/community-maps/Pine_Barrens_Ecoregion_Map.pdf",
    abstractPdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Pine_Barrens.pdf",
    mnfiUrl: "https://mnfi.anr.msu.edu/communities/description/10694/pine-barrens"
  },
  {
    communityId: 10653,
    placesToVisit: [
    "Nine Mile Swamp, Roscommon State Forest Management Unit, Roscommon Co.",
    "Prison Camp Swamp, Tahquamenon Falls State Park, Luce Co.",
    "Sylvania, Sylvania Wilderness and Recreation Area, Ottawa National Forest, Gogebic Co.",
    "Tahqua Trail Swamp, Tahquamenon Falls State Park, Chippewa Co.",
    "Waterloo Black Spruce Bog, Waterloo State Recreation Area, Jackson Co."
  ],
    literature: [],
    photoUrl: null,
    countyMapUrl: "https://mnfi.anr.msu.edu/community-maps/County_10653.png",
    ecoregionMapUrl: "https://mnfi.anr.msu.edu/community-maps/Poor_Conifer_Swamp_Ecoregion_Map.pdf",
    abstractPdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Poor_Conifer_Swamp.pdf",
    mnfiUrl: "https://mnfi.anr.msu.edu/communities/description/10653/poor-conifer-swamp"
  },
  {
    communityId: 10662,
    placesToVisit: [
    "Cyr Fen, Escanaba State Forest Management Unit, Marquette Co.",
    "Lovell's Fen, Grayling State Forest Management Unit, Crawford Co.",
    "Nahma Fen, Hiawatha National Forest, Delta Co.",
    "Nine Mile Fen, Roscommon State Forest Management Unit, Roscommon Co.",
    "Snow Lake Fen, Barry State Game Area, Barry Co.",
    "Tahquamenon River Mouth Fen, Tahquamenon Falls State Park, Chippewa Co."
  ],
    literature: [],
    photoUrl: null,
    countyMapUrl: "https://mnfi.anr.msu.edu/community-maps/County_10662.png",
    ecoregionMapUrl: "https://mnfi.anr.msu.edu/community-maps/Poor_Fen_Ecoregion_Map.pdf",
    abstractPdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Poor_Fen.pdf",
    mnfiUrl: "https://mnfi.anr.msu.edu/communities/description/10662/poor-fen"
  },
  {
    communityId: 10667,
    placesToVisit: [
    "Algoe Lake Fen, Ortonville State Recreation Area, Lapeer Co.",
    "Brandt Road Fen and Halstead Lake, Holly State Recreation Area, Oakland Co.",
    "Hill Creek Fen (Great Fen) and Shaw Lake Fen, Barry State Game Area, Barry Co.",
    "Ives Road Fen Preserve, The Nature Conservancy, Lenawee Co.",
    "Little Goose Lake Fen, Michigan Nature Association (Goose Creek Grasslands Nature",
    "Sanctuary), Lenawee Co.",
    "Long Lake Fen, Springfield Township (Shiawassee Basin Preserve), Oakland Co.",
    "Marsh Brook Fen, Watkins Lake State Park, Jackson Co.",
    "Park Lyndon Fen, Pinckney State Recreation Area and Washtenaw County Park,",
    "Washtenaw Co.",
    "Paw Paw Prairie Fen Preserve, The Nature Conservancy, Van Buren Co."
  ],
    literature: [],
    photoUrl: null,
    countyMapUrl: "https://mnfi.anr.msu.edu/community-maps/County_10667.png",
    ecoregionMapUrl: "https://mnfi.anr.msu.edu/community-maps/Prairie_Fen_Ecoregion_Map.pdf",
    abstractPdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Prairie_Fen.pdf",
    mnfiUrl: "https://mnfi.anr.msu.edu/communities/description/10667/prairie-fen"
  },
  {
    communityId: 10652,
    placesToVisit: [
    "Bear River Swamp, Gaylord State Forest Management Unit, Emmet Co.",
    "Deadstream Swamp, Roscommon State Forest Management Unit, Roscommon Co.",
    "Gogomain Swamp, Sault Sainte Marie State Forest Management Unit, Chippewa Co.",
    "Green Swamp, Atlanta State Forest Management Unit, Otsego Co. and Montmorency Co.",
    "Lakeville Swamp Nature Sanctuary, Michigan Nature Association, Oakland Co.",
    "Minnehaha Creek, Gaylord State Forest Management Unit, Emmet Co.",
    "Pierce Cedar Creek Institute, Barry Co.",
    "Watson Swamp, Traverse City State Forest Management Unit, Kalkaska Co."
  ],
    literature: [],
    photoUrl: null,
    countyMapUrl: "https://mnfi.anr.msu.edu/community-maps/County_10652.png",
    ecoregionMapUrl: "https://mnfi.anr.msu.edu/community-maps/Rich_Conifer_Swamp_Ecoregion_Map.pdf",
    abstractPdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Rich_Conifer_Swamp.pdf",
    mnfiUrl: "https://mnfi.anr.msu.edu/communities/description/10652/rich-conifer-swamp"
  },
  {
    communityId: 10660,
    placesToVisit: [
    "East Branch Fox River, Shingleton State Forest Management Unit, Schoolcraft Co.",
    "Embury Road Swamp, Waterloo State Recreation Area and Park Lyndon (Washtenaw County Park), Washtenaw Co.",
    "Hudson Mills Tamarack Swamp, Hudson Mills Metropark, Washtenaw Co.",
    "Little Portage Lake Swamp, Waterloo State Recreation Area, Jackson Co.",
    "Leeke Lake Swamp, Waterloo State Recreation Area, Jackson Co.",
    "Lower Tomahawk Lake, Atlanta State Forest Management Unit, Montmorency Co.",
    "Pierce Cedar Creek Institute, Barry Co.",
    "Tamarack Trail Swamp, Kensington Metropark, Oakland Co."
  ],
    literature: [],
    photoUrl: null,
    countyMapUrl: "https://mnfi.anr.msu.edu/community-maps/County_10660.png",
    ecoregionMapUrl: "https://mnfi.anr.msu.edu/community-maps/Rich_Tamarack_Swamp_Ecoregion_Map.pdf",
    abstractPdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Rich_Tamarack_Swamp.pdf",
    mnfiUrl: "https://mnfi.anr.msu.edu/communities/description/10660/rich-tamarack-swamp"
  },
  {
    communityId: 10714,
    placesToVisit: [
    "Little Presque Isle, Gwinn State Forest Management Unit, Marquette Co.",
    "Nordhouse Dunes, Ludington State Park and Manistee National Forest, Mason Co.",
    "Pictured Rocks, Pictured Rocks National Lakeshore, Alger Co.",
    "Sleeping Bear Dunes, Sleeping Bear Dunes National Lakeshore, Leelanau Co.",
    "Sleeping Misery Bay, Baraga State Forest Management Unit, Ontonagon Co.",
    "South Manitou Island, Sleeping Bear Dunes National Lakeshore, Leelanau Co.",
    "Twelve Mile Beach, Pictured Rocks National Lakeshore, Alger Co."
  ],
    literature: [],
    photoUrl: null,
    countyMapUrl: "https://mnfi.anr.msu.edu/community-maps/County_10714.png",
    ecoregionMapUrl: "https://mnfi.anr.msu.edu/community-maps/Sand_and_Gravel_Beach_Ecoregion_Map.pdf",
    abstractPdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Sand_and_Gravel_Beach.pdf",
    mnfiUrl: "https://mnfi.anr.msu.edu/communities/description/10714/sand-and-gravel-beach"
  },
  {
    communityId: 18988,
    placesToVisit: [
    "Point Abbaye, Baraga State Forest Management Unit, Baraga Co.",
    "Pictured Rocks, Pictured Rocks National Lakeshore, Alger Co.",
    "Porcupine Shore, Porcupine Mountains Wilderness State Park, Ontonagon Co.",
    "Sleeping Misery Bay, Baraga State Forest Management Unit, Ontonagon Co."
  ],
    literature: [],
    photoUrl: null,
    countyMapUrl: "https://mnfi.anr.msu.edu/community-maps/County_18988.png",
    ecoregionMapUrl: "https://mnfi.anr.msu.edu/community-maps/Sandstone_Bedrock_Lakeshore_Ecoregion_Map.pdf",
    abstractPdfUrl: null,
    mnfiUrl: "https://mnfi.anr.msu.edu/communities/description/18988/sandstone-bedrock-lakeshore"
  },
  {
    communityId: 18997,
    placesToVisit: [
    "Black River Gorge, Ottawa National Forest, Gogebic Co.",
    "Fitzgerald Park, Eaton County Parks Department, Eaton Co.",
    "Laughing Whitefish Falls, Laughing Whitefish Falls State Park, Alger Co.",
    "Miners Falls Cliffs, Pictured Rocks National Lakeshore, Alger Co.",
    "Mosquito River Gorge, Pictured Rocks National Lakeshore, Alger Co.",
    "Presque Isle River, Porcupine Mountains Wilderness State Park, Gogebic Co.",
    "Tahquamenon Falls, Tahquamenon Falls State Park, Luce Co."
  ],
    literature: [],
    photoUrl: null,
    countyMapUrl: "https://mnfi.anr.msu.edu/community-maps/County_18997.png",
    ecoregionMapUrl: "https://mnfi.anr.msu.edu/community-maps/Sandstone_Cliff_Ecoregion_Map.pdf",
    abstractPdfUrl: null,
    mnfiUrl: "https://mnfi.anr.msu.edu/communities/description/18997/sandstone-cliff"
  },
  {
    communityId: 18985,
    placesToVisit: [
    "Point Abbaye, Baraga State Forest Management Unit, Baraga Co.",
    "Porcupine Shore, Porcupine Mountains Wilderness State Park, Ontonagon Co.",
    "Sleeping Misery Bay, Baraga State Forest Management Unit, Ontonagon Co."
  ],
    literature: [],
    photoUrl: null,
    countyMapUrl: "https://mnfi.anr.msu.edu/community-maps/County_18985.png",
    ecoregionMapUrl: "https://mnfi.anr.msu.edu/community-maps/Sandstone_Cobble_Shore_Ecoregion_Map.pdf",
    abstractPdfUrl: null,
    mnfiUrl: "https://mnfi.anr.msu.edu/communities/description/18985/sandstone-cobble-shore"
  },
  {
    communityId: 10719,
    placesToVisit: [
    "Little Presque Isle, Gwinn State Forest Management Unit, Marquette Co.",
    "Pictured Rocks, Pictured Rocks National Lakeshore, Alger Co.",
    "Point Abbaye, Baraga State Forest Management Unit, Baraga Co.",
    "Rabbit Bay, Baraga State Forest Management Unit, Houghton Co."
  ],
    literature: [],
    photoUrl: null,
    countyMapUrl: "https://mnfi.anr.msu.edu/community-maps/County_10719.png",
    ecoregionMapUrl: "https://mnfi.anr.msu.edu/community-maps/Sandstone_Lakeshore_Cliff_Ecoregion_Map.pdf",
    abstractPdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Sandstone_Lakeshore_Cliff.pdf",
    mnfiUrl: "https://mnfi.anr.msu.edu/communities/description/10719/sandstone-lakeshore-cliff"
  },
  {
    communityId: 10707,
    placesToVisit: [
    "Fiborn Karst, Sault Sainte Marie State Forest Management Unit and Michigan Karst Conservancy, Mackinac Co.",
    "Rockport Karst, Rockport State Recreation Area, Presque Isle Co.",
    "Tomahawk Sinkholes, Sinkholes Pathway, Atlanta State Forest Management Unit, Presque Isle Co."
  ],
    literature: [],
    photoUrl: null,
    countyMapUrl: "https://mnfi.anr.msu.edu/community-maps/County_10707.png",
    ecoregionMapUrl: "https://mnfi.anr.msu.edu/community-maps/Sinkhole_Ecoregion_Map.pdf",
    abstractPdfUrl: null,
    mnfiUrl: "https://mnfi.anr.msu.edu/communities/description/10707/sinkhole"
  },
  {
    communityId: 10655,
    placesToVisit: [
    "Haven Hill, Highland State Recreation Area, Oakland Co.",
    "Huron Swamp, Indian Springs Metropark, Oakland Co.",
    "Sheldon Forest, Stony Creek Metropark, Oakland Co.",
    "Tobico Swamp, Tobico State Game Area, Bay Co."
  ],
    literature: [],
    photoUrl: null,
    countyMapUrl: "https://mnfi.anr.msu.edu/community-maps/County_10655.png",
    ecoregionMapUrl: "https://mnfi.anr.msu.edu/community-maps/Southern_Hardwood_Swamp_Ecoregion_Map.pdf",
    abstractPdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Southern_Hardwood_Swamp.pdf",
    mnfiUrl: "https://mnfi.anr.msu.edu/communities/description/10655/southern-hardwood-swamp"
  },
  {
    communityId: 10676,
    placesToVisit: [
    "Chamberlain Lakes, Bald Mountain State Recreation Area, Oakland Co.",
    "Williams Lake, Yankee Springs State Recreation Area, Barry Co."
  ],
    literature: [],
    photoUrl: null,
    countyMapUrl: "https://mnfi.anr.msu.edu/community-maps/County_10676.png",
    ecoregionMapUrl: "https://mnfi.anr.msu.edu/community-maps/Southern_Shrub-carr_Ecoregion_Map.pdf",
    abstractPdfUrl: null,
    mnfiUrl: "https://mnfi.anr.msu.edu/communities/description/10676/southern-shrub-carr"
  },
  {
    communityId: 10657,
    placesToVisit: [
    "Graham Lakes, Bald Mountain State Recreation Area, Oakland Co.",
    "Havens Road Meadow and Bassett Lake Meadow, Barry State Game Area, Barry Co.",
    "Indian Springs Wet Meadow, Indian Springs Metropark, Oakland Co.",
    "Mill Creek Wet Meadow, Three Rivers State Game Area, St. Joseph Co.",
    "Moss Lake, Proud Lake State Recreation Area, Oakland Co.",
    "Riethmiller Road Wet Meadow, Waterloo State Recreation Area, Jackson Co."
  ],
    literature: [],
    photoUrl: null,
    countyMapUrl: "https://mnfi.anr.msu.edu/community-maps/County_10657.png",
    ecoregionMapUrl: "https://mnfi.anr.msu.edu/community-maps/Southern_Wet_Meadow_Ecoregion_Map.pdf",
    abstractPdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Southern_Wet_Meadow.pdf",
    mnfiUrl: "https://mnfi.anr.msu.edu/communities/description/10657/southern-wet-meadow"
  },
  {
    communityId: 10651,
    placesToVisit: [
    "Forked Lake Marsh, Crane Pond State Game Area, Cass Co.",
    "Lake of the Clouds, Porcupine Mountains Wilderness State Park, Ontonagon Co.",
    "Otis Lake Marsh, Barry State Game Area, Barry Co."
  ],
    literature: [],
    photoUrl: null,
    countyMapUrl: "https://mnfi.anr.msu.edu/community-maps/County_10651.png",
    ecoregionMapUrl: "https://mnfi.anr.msu.edu/community-maps/Submergent_Marsh_Ecoregion_Map.pdf",
    abstractPdfUrl: null,
    mnfiUrl: "https://mnfi.anr.msu.edu/communities/description/10651/submergent-marsh"
  },
  {
    communityId: 10715,
    placesToVisit: [
    "Bare Bluffs Glade, Michigan Nature Association (Grinnell Memorial Sanctuary at Bare Bluff), Keweenaw Co.",
    "Fish Cove, Baraga State Forest Management Unit, Keweenaw Co.",
    "Isle Royale National Park, Keweenaw Co.",
    "Horseshoe Harbor, The Nature Conservancy (Mary Macdonald Preserve at Horseshoe Harbor), Keweenaw Co.",
    "Porcupine Mountain Glades, Porcupine Mountains Wilderness State Park, Ontonagon Co.",
    "Traps Hills Escarpment, Ottawa National Forest, Ontonagon Co."
  ],
    literature: [],
    photoUrl: null,
    countyMapUrl: "https://mnfi.anr.msu.edu/community-maps/County_10715.png",
    ecoregionMapUrl: "https://mnfi.anr.msu.edu/community-maps/Volcanic_Bedrock_Glade_Ecoregion_Map.pdf",
    abstractPdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Volcanic_Bedrock_Glade.pdf",
    mnfiUrl: "https://mnfi.anr.msu.edu/communities/description/10715/volcanic-bedrock-glade"
  },
  {
    communityId: 10716,
    placesToVisit: [
    "Bete Grise, Bear Bluff, and Big Bay West, Baraga State Forest Management Unit, Keweenaw Co.",
    "Copper Harbor Lighthouse and Porters Island, Fort Wilkins State Historic Park, Keweenaw Co.",
    "Horseshoe Harbor, The Nature Conservancy (Mary Macdonald Preserve at Horseshoe Harbor), Keweenaw Co.",
    "Isle Royale National Park, Keweenaw Co.",
    "Keweenaw Point, High Rock, and Keystone Bay, Baraga State Forest Management Unit, Keweenaw Co.",
    "Porcupine Shore, Porcupine Mountains Wilderness State Park, Ontonagon Co."
  ],
    literature: [],
    photoUrl: null,
    countyMapUrl: "https://mnfi.anr.msu.edu/community-maps/County_10716.png",
    ecoregionMapUrl: "https://mnfi.anr.msu.edu/community-maps/Volcanic_Bedrock_Lakeshore_Ecoregion_Map.pdf",
    abstractPdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Volcanic_Bedrock_Lakeshore.pdf",
    mnfiUrl: "https://mnfi.anr.msu.edu/communities/description/10716/volcanic-bedrock-lakeshore"
  },
  {
    communityId: 19000,
    placesToVisit: [
    "Bare Bluffs Cliffs, Michigan Nature Association (Grinnell Memorial Sanctuary at Bare Bluff), Keweenaw Co.",
    "Escarpment Trail Cliffs, Porcupine Mountains Wilderness State Park, Gogebic Co. and Ontonagon Co.",
    "Isle Royale National Park, Keweenaw Co.",
    "Traps Hills Escarpment, Ottawa National Forest, Ontonagon Co."
  ],
    literature: [],
    photoUrl: null,
    countyMapUrl: "https://mnfi.anr.msu.edu/community-maps/County_19000.png",
    ecoregionMapUrl: "https://mnfi.anr.msu.edu/community-maps/Volcanic_Cliff_Ecoregion_Map.pdf",
    abstractPdfUrl: null,
    mnfiUrl: "https://mnfi.anr.msu.edu/communities/description/19000/volcanic-cliff"
  },
  {
    communityId: 18994,
    placesToVisit: [
    "High Rock Bay, Baraga State Forest Management Unit, Keweenaw Co.",
    "Isle Royale National Park, Keweenaw Co.",
    "Keweenaw Point, Baraga State Forest Management Unit, Keweenaw Co.",
    "Porcupine Shore, Porcupine Mountains Wilderness State Park, Ontonagon Co."
  ],
    literature: [],
    photoUrl: null,
    countyMapUrl: "https://mnfi.anr.msu.edu/community-maps/County_18994.png",
    ecoregionMapUrl: "https://mnfi.anr.msu.edu/community-maps/Volcanic_Cobble_Shore_Ecoregion_Map.pdf",
    abstractPdfUrl: null,
    mnfiUrl: "https://mnfi.anr.msu.edu/communities/description/18994/volcanic-cobble-shore"
  },
  {
    communityId: 10723,
    placesToVisit: [
    "Bare Bluffs Cliffs, Michigan Nature Association (Grinnell Memorial Sanctuary at Bare Bluff), Keweenaw Co.",
    "Bete Grise, Michigan Nature Association (Grinnell Memorial Sanctuary at Bare Bluff), Keweenaw Co.",
    "Isle Royale National Park, Keweenaw Co.",
    "Manitou Island, Baraga State Forest Management Unit, Keweenaw Co."
  ],
    literature: [],
    photoUrl: null,
    countyMapUrl: "https://mnfi.anr.msu.edu/community-maps/County_10723.png",
    ecoregionMapUrl: "https://mnfi.anr.msu.edu/community-maps/Volcanic_Lakeshore_Cliff_Ecoregion_Map.pdf",
    abstractPdfUrl: null,
    mnfiUrl: "https://mnfi.anr.msu.edu/communities/description/10723/volcanic-lakeshore-cliff"
  },
  {
    communityId: 10665,
    placesToVisit: [
    "Turner Creek Wet Prairie, Barry State Game Area, Barry Co.",
    "Waterloo Wet Prairie, Waterloo State Recreation Area, Jackson Co."
  ],
    literature: [],
    photoUrl: null,
    countyMapUrl: "https://mnfi.anr.msu.edu/community-maps/County_10665.png",
    ecoregionMapUrl: "https://mnfi.anr.msu.edu/community-maps/Wet_Prairie_Ecoregion_Map.pdf",
    abstractPdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Wet_Prairie.pdf",
    mnfiUrl: "https://mnfi.anr.msu.edu/communities/description/10665/wet-prairie"
  },
  {
    communityId: 19009,
    placesToVisit: [
    "Belle Isle Flatwoods, Detroit Recreation Department, Wayne Co.",
    "Salamander Woods, Oakwoods Metropark, Wayne Co.",
    "Kuntsman Road Swamp, Wolcott Mill Metropark, Macomb Co."
  ],
    literature: [],
    photoUrl: null,
    countyMapUrl: "https://mnfi.anr.msu.edu/community-maps/County_19009.png",
    ecoregionMapUrl: "https://mnfi.anr.msu.edu/community-maps/Wet-mesic_Flatwoods_Ecoregion_Map.pdf",
    abstractPdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Wet-mesic_Flatwoods.pdf",
    mnfiUrl: "https://mnfi.anr.msu.edu/communities/description/19009/wet-mesic-flatwoods"
  },
  {
    communityId: 10674,
    placesToVisit: [
    "Hudson Mills Wet-mesic Prairie, Hudson Mills Metropark, Washtenaw Co.",
    "Indian Springs Wet-mesic Prairie, Indian Springs Metropark, Oakland Co.",
    "Pinckney Prairie, Pinckney State Recreation Area, Jackson Co.",
    "Williamsville Lake Prairie, Unadilla Wildlife Area, Livingston Co."
  ],
    literature: [],
    photoUrl: null,
    countyMapUrl: "https://mnfi.anr.msu.edu/community-maps/County_10674.png",
    ecoregionMapUrl: "https://mnfi.anr.msu.edu/community-maps/Wet-mesic_Prairie_Ecoregion_Map.pdf",
    abstractPdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Wet-mesic_Prairie.pdf",
    mnfiUrl: "https://mnfi.anr.msu.edu/communities/description/10674/wet-mesic-prairie"
  },
  {
    communityId: 10682,
    placesToVisit: [
    "Lidkey Swamp Prairie, Manistee National Forest, Oceana Co.",
    "Muskegon Wet-mesic Sand Prairie, Muskegon State Game Area, Newaygo Co.",
    "Portage Creek Complex, Grayling State Forest Management Unit, and Traverse City State Forest Management Unit, Crawford Co. and Kalkaska Co.",
    "Tussing Prairie, Manistee National Forest, Lake Co."
  ],
    literature: [],
    photoUrl: null,
    countyMapUrl: "https://mnfi.anr.msu.edu/community-maps/County_10682.png",
    ecoregionMapUrl: "https://mnfi.anr.msu.edu/community-maps/Wet-mesic_Sand_Prairie_Ecoregion_Map.pdf",
    abstractPdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Wet-Mesic_Sand_Prairie.pdf",
    mnfiUrl: "https://mnfi.anr.msu.edu/communities/description/10682/wet-mesic-sand-prairie"
  },
  {
    communityId: 10679,
    placesToVisit: [
    "Big Knob Campground, Sault Sainte Marie State Forest Management Unit, Mackinac Co.",
    "Gulliver Lake Dunes, Shingleton State Forest Management Unit, Schoolcraft Co.",
    "Little Presque Isle Point, Gwinn State Forest Management Unit, Marquette Co.",
    "Platte Bay, Sleeping Bear Dunes National Lakeshore, Benzie Co.",
    "Pointe Aux Chenes, Hiawatha National Forest, Mackinac Co.",
    "Port Crescent, Port Crescent State Park, Huron Co.",
    "Scott Point, Sault Sainte Marie State Forest Management Unit, Mackinac Co.",
    "Sturgeon Bay, Wilderness State Park, Emmett Co.",
    "Whitefish Point, Newberry State Forest Management Unit, Chippewa Co."
  ],
    literature: [],
    photoUrl: null,
    countyMapUrl: "https://mnfi.anr.msu.edu/community-maps/County_10679.png",
    ecoregionMapUrl: "https://mnfi.anr.msu.edu/community-maps/Wooded_Dune_and_Swale_Complex_Ecoregion_Map.pdf",
    abstractPdfUrl: "https://mnfi.anr.msu.edu/abstracts/ecology/Wooded_Dune_and_Swale_Complex.pdf",
    mnfiUrl: "https://mnfi.anr.msu.edu/communities/description/10679/wooded-dune-and-swale-complex"
  },
];
