// AUTO-GENERATED by lib/internal-data-providers/src/mnfi/scraper — do not edit manually.
// Scraped from https://mnfi.anr.msu.edu on 2026-06-29.

export const MNFI_SCRAPED_AT = "2026-06-29T23:48:59.860Z";
