import { pgTable, serial, text, timestamp, jsonb } from "drizzle-orm/pg-core";

export const natureserveSpeciesCacheTable = pgTable("natureserve_species_cache", {
  id: serial("id").primaryKey(),
  cache_key: text("cache_key").notNull().unique(),
  scientific_name: text("scientific_name"),
  common_name: text("common_name"),
  global_rank: text("global_rank"),
  rounded_global_rank: text("rounded_global_rank"),
  national_rank: text("national_rank"),
  rounded_national_rank: text("rounded_national_rank"),
  state_code: text("state_code"),
  state_rank: text("state_rank"),
  rounded_state_rank: text("rounded_state_rank"),
  iucn_category: text("iucn_category"),
  iucn_description: text("iucn_description"),
  federal_status: text("federal_status"),
  federal_status_description: text("federal_status_description"),
  state_status: text("state_status"),
  cites_description: text("cites_description"),
  cosewic_code: text("cosewic_code"),
  cosewic_description: text("cosewic_description"),
  natureserve_url: text("natureserve_url"),
  element_global_id: text("element_global_id"),
  raw_summary: jsonb("raw_summary").default({}),
  expires_at: timestamp("expires_at", { withTimezone: true }),
  source_id: text("source_id").notNull().default("natureserve"),
  fetched_at: timestamp("fetched_at", { withTimezone: true }).notNull(),
  method: text("method").notNull().default("api_fetch"),
  upstream_url: text("upstream_url").notNull(),
  general_summary: text("general_summary").notNull(),
  technical_details: text("technical_details").notNull(),
  created_at: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
});

export const natureserveEcosystemsCacheTable = pgTable("natureserve_ecosystems_cache", {
  id: serial("id").primaryKey(),
  cache_key: text("cache_key").notNull().unique(),
  results: jsonb("results").notNull().default([]),
  result_count: text("result_count"),
  expires_at: timestamp("expires_at", { withTimezone: true }),
  source_id: text("source_id").notNull().default("natureserve"),
  fetched_at: timestamp("fetched_at", { withTimezone: true }).notNull(),
  method: text("method").notNull().default("api_fetch"),
  upstream_url: text("upstream_url").notNull(),
  general_summary: text("general_summary").notNull(),
  technical_details: text("technical_details").notNull(),
  created_at: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
});
